### PR TITLE
[efr32] Radio: don't abort current operation on switching to idle

### PR DESCRIPTION
**Pull request by dismirlian**
On the RAIL callback, received packets are held and passed to OT core in the event loop.

On a sleepy device, if there is nothing more to do, the OT core calls `otPlatRadioSleep` which in turn calls `RAIL_Idle(gRailHandle, RAIL_IDLE_ABORT, true)`.

If the time between `RAIL_EVENT_RX_PACKET_RECEIVED` and the call to `RAIL_Idle` is less than the turnaround + the ACK tx time, the call to `RAIL_Idle` aborts the auto-ack that was being transmitted by the radio, so there are received packets without ACK, like this:

image

<pre>
[0012727105] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012727111] [WARN]-PLAT----: RX_PACKET_RECEIVED
[0012727112] [WARN]-PLAT----: <b>TXACK_ABORTED</b>
[0012727998] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012728008] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012728019] [WARN]-PLAT----: RX_PACKET_RECEIVED
[0012728020] [WARN]-PLAT----: TXACK_PACKET_SENT
[0012728030] [WARN]-PLAT----: RX_PACKET_RECEIVED
[0012728030] [WARN]-PLAT----: TXACK_PACKET_SENT
[0012728042] [WARN]-PLAT----: RX_PACKET_RECEIVED
[0012728042] [WARN]-PLAT----: TXACK_PACKET_SENT
[0012728055] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012728153] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012728159] [WARN]-PLAT----: RX_PACKET_RECEIVED
[0012728160] [WARN]-PLAT----: <b>TXACK_ABORTED</b>
[0012736995] [WARN]-PLAT----: RX_ACK_RECEIVED
</pre>

This PR changes that call so that `RAIL_Idle` waits for the last operation to finish. With this change, the ACK is always sent.

### CODE REVIEW

**Comment by rerasool** [comment]
Thanks @dismirlian ! 
Could you please make this change for [efr32**mg13** radio.c](https://github.com/openthread/openthread/blob/master/examples/platforms/efr32mg13/radio.c) file as well? Then I can run some internal tests and get this pull request approved.

**Comment by dismirlian** [comment]
Hi @rerasool, of course. I commited this change to the mg13 radio driver.

Please note that the mg13 radio driver is missing some modifications from previous PRs (see #4482, #4484, #4506).

**Comment by rerasool** [comment]
@dismirlian could you please make those changes as well for mg13? I can then run internal tests and get this pull request approved.

@jwhui could you please add me as a reviewer? I work with @nigelg-silabs at Silicon Labs.

**Comment by jwhui** [comment]
> @dismirlian could you please make those changes as well for mg13? I can then run internal tests and get this pull request approved.

I believe @dismirlian indicated that he made updates for mg13 in 504015e.

> @jwhui could you please add me as a reviewer? I work with @nigelg-silabs at Silicon Labs.

Just sent an invite.

**Comment by romacdon** [comment]
> I believe @dismirlian indicated that he made updates for mg13 in [504015e](https://github.com/openthread/openthread/commit/504015e7daa339848e0de8fae07482431f120c17).

@jwhui and @dismirlian - to be clear @rerasool is asking for the 3 additional PRs mentioned in this comment https://github.com/openthread/openthread/pull/4586#issuecomment-589822261  to be added to the mg13 code now.

**Comment by dismirlian** [comment]
Hi all. Ok, I'll make the same modifications to the mg13 driver. The bottom line is that the code is 99% the same in all the efr32xxx platforms (RAIL and EMLIB/EMDRV already abstract almost all the platform details, so why not have a common OT platform abstraction layer for all the efr32?) @nigelg-silabs confirmed there is an ongoing unification effort.

@rerasool Do you want me to open a separate PR?

Note: I don't have mg13 hardware to test...

**Comment by romacdon** [comment]
Thanks @dismirlian. I just spoke with @rerasool. What we'd like to see is that all the changes go into this one PR.  The reason is that it makes things a little easier from our end. @rerasool  can then easily create two test images against this one PR, one for mg12 and one for mg13, and verify the changes at one time.

As for the combing the platform abstraction.  We agree that is the desired solution.  I will follow up with @nigelg-silabs to see where that effort is and to see if we can get that pushed in over the next few weeks.

Thanks for all your help.

**Comment by dismirlian** [comment]
Hi @romacdon, I applied the changes from those 3 PRs to the mg13 radio driver. Please let me know if I can help with anything else.

**Comment by romacdon** [comment]
Thanks @dismirlian.  I don't think there's anything we need you to do right now.  @rerasool will build images for both mg12 and mg13 and do some testing. If all goes well then he'll approve the PR.  Thanks again.

**Comment by dismirlian** [comment]
@rerasool Just curious, what tests do you run?

**Comment by rerasool** [comment]
@dismirlian Our QA team found this issue using [GRL Thread Test Harness](https://graniteriverlabs.com/thread/), which is the requirement for Thread certification.  From this test suite, the following test cases hit this problem:
* SED 9.2.13
* Leader 5.6.6
* Router 5.6.9

After applying your changes, these test cases passed!

**Pull request merged**
