### PR TITLE
NcpBase: Change/Fix the set/get property handlers for NET_STAT

### PR DESCRIPTION
**Pull request by abtink**
This commit addresses some issues with the set/get property handlers of `NET_STAT` to ensure that wpantund/wpanctl commands "join"/"leave" operate as expected.

### CODE REVIEW

**Comment by arjunasiva** [comment]
LGTM

**Comment by darconeous** [comment]
👍

**Comment by mszczodrak** [comment]
LGTM 👍

**Comment by jwhui** [comment]
LGTM :+1:

**Pull request merged**
