### PR TITLE
Add platform API to check state of the radio.

### PR DESCRIPTION
**Pull request by hubertmis**

### CODE REVIEW

**Comment by jwhui** [comment]
Overall, I think this PR looks good.  Do you have plans to use `otPlatRadioGetState()` within OpenThread?  Or is this more for diagnostics/debugging platform drivers?  One design goal for the `otPlat*()` APIs was to limit them to what is actually required by OpenThread, making it easy for platform developers to know what functions must be implemented.  We can revisit that design decision if others feel otherwise.

**Comment by hubertmis** [comment]
I'm using this API in an application. I don't think it will be needed in the network stack (maybe debugging). If the design goal is to keep platform API as simple as possible, I could call radio driver directly from the application. But it looks cleaner to use `platform/radio.h` API instead.

**Comment by jwhui** [comment]
I'm fine with keeping the existing function.  Maybe worth adding to the doxygen that this function is not actually required by OpenThread, but may be used for debugging purposes and/or application-specific purposes.

**Comment by hubertmis** [comment]
I updated the doxygen.

**Pull request merged**
