### PR TITLE
[script] fix arm-gcc toolchain install on ubuntu

### LINKED ISSUE #5554: "PRIx64" compile error on Ubuntu 20
**Describe the bug** 
Compiling openthread libraries and examples fails with the following error:
```
/openthread/examples/../src/cli/cli_joiner.cpp: In member function 'otError ot::Cli::Joiner::ProcessDiscerner(uint8_t, char**)':
/openthread/examples/../src/cli/cli_joiner.cpp:76:38: error: expected ')' before 'PRIx64'
   76 |         mInterpreter.OutputLine("0x%" PRIx64 "/%u", discerner->mValue, discerner->mLength);
      |                                ~     ^~~~~~~
      |                                      )
  CXX      libopenthread_cli_ftd_a-cli_network_data.o
```

It appears to be an issue with the PRIx64 macro and inttypes.h/cinttypes. Replacing the define with `<cinttypes>`, as well as defining the macro `__STDC_FORMAT_MACROS` as mentioned [here ](https://github.com/Microsoft/rDSN/issues/197) did not fix this issue.

**To Reproduce**

1. Git commit id: **0d8a99b**
2. IEEE 802.15.4 hardware platform: **NRF52840**
3. Build steps:
I am building on a newly created Ubuntu 20 VM, using these commands:
```
./script/bootstrap
./bootstrap
make -f examples/Makefile-nrf52840 BORDER_AGENT=1 BORDER_ROUTER=1 COAP=1 COMMISSIONER=1 DISABLE_BUILTIN_MBEDTLS=1 DNS_CLIENT=1 DIAGNOSTIC=1 EXTERNAL_HEAP=1 JOINER=1 LINK_RAW=1 MAC_FILTER=1 MTD_NETDIAG=1 SERVICE=1 UDP_FORWARD=1 ECDSA=1 SNTP_CLIENT=1 COAPS=1 DHCP6_SERVER=1 DHCP6_CLIENT=1
```
4. Network topology: N/A

**Expected behavior** 
I would expect the build to complete successfully.

### PR DESCRIPTION
**Pull request by jwhui**
Fixes #5554

### CODE REVIEW

**Review by abtink — APPROVED** [review]
LGTM.

**Comment by lmnotran** [comment]
I'm getting a cert error

```
+ wget -c https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
--2020-10-07 13:58:38--  https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
Resolving developer.arm.com (developer.arm.com)... 104.77.251.191
Connecting to developer.arm.com (developer.arm.com)|104.77.251.191|:443... connected.
ERROR: cannot verify developer.arm.com's certificate, issued by 'CN=GlobalSign Extended Validation CA - SHA256 - G3,O=GlobalSign nv-sa,C=BE':
  Unable to locally verify the issuer's authority.
To connect to developer.arm.com insecurely, use `--no-check-certificate'.
```

**Comment by jwhui** [comment]
> @jwhui I'm getting a cert error
> 
> ```
> + wget -c https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
> --2020-10-07 13:58:38--  https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
> Resolving developer.arm.com (developer.arm.com)... 104.77.251.191
> Connecting to developer.arm.com (developer.arm.com)|104.77.251.191|:443... connected.
> ERROR: cannot verify developer.arm.com's certificate, issued by 'CN=GlobalSign Extended Validation CA - SHA256 - G3,O=GlobalSign nv-sa,C=BE':
>   Unable to locally verify the issuer's authority.
> To connect to developer.arm.com insecurely, use `--no-check-certificate'.
> ```

@lmnotran , it may be that your CA certs are out-of-date. Can you try `sudo apt-get install ca-certificates`before running `./script/bootstrap`?

**Comment by lmnotran** [comment]
@jwhui Ahh, you're right. Installing `ca-certificates` before running `./script/bootstrap` fixed it. Thanks again for the help! :)

**Pull request merged**
