### PR TITLE
[windows] remove unsupported platform

### PR DESCRIPTION
**Pull request by KaSroka**
This is the "initial stab" as mentioned in #3874. Probably more changes can be done so feel free to comment or contribute.

TODO:
- [x] Remove `include/openthread-windows-config.h`.
- [x] Remove `include/openthread/platform/logging-windows.h`.
- [x] Remove `_KERNEL_MODE` `#ifdef` blocks.
- [x] Remove `WINDOWS_LOGGING` `#ifdef` blocks.
- [x] Remove `OT_STRING_WINDOWS_WORKAROUND` block.
- [x] Remove `WPP_NAME`.
- [x] Remove `tests/scripts/thread-cert/node_api.py` and collapse `tests/scripts/thread-cert/node_cli.py` back into `tests/scripts/thread-cert/node.py`
- [x] Remove `SnifferVirtualTransport` from `tests/scripts/thread-cert/sniffer_transport.py`
- [x] Remove `_MSC_VER` `#ifdef` blocks.
- [x] Remove `wrap_stdint.h` as it's not needed now.
- [x] Remove windows images from `doc/images`.
- [x] Remove `node_api.py`.

### CODE REVIEW

**Comment by KaSroka** [comment]
I just want to emphasize that this is my after work activity.

**Comment by jwhui** [comment]
Thanks for contributing these changes!

Some things to consider:
1. It seems `etc/` was completely removed. I think you meant to only remove `etc/visual-studio`.
1. Remove `include/openthread-windows-config.h`.
1. Remove `include/openthread/platform/logging-windows.h`.
1. Remove `_KERNEL_MODE` `#ifdef` blocks.
1. Remove `WINDOWS_LOGGING` `#ifdef` blocks.
1. Remove `OT_STRING_WINDOWS_WORKAROUND` block.
1. Remove `WPP_NAME`.
1. Remove `tests/scripts/thread-cert/node_api.py` and collapse `tests/scripts/thread-cert/node_cli.py` back into `tests/scripts/thread-cert/node.py`
1. Remove `SnifferVirtualTransport` from `tests/scripts/thread-cert/sniffer_transport.py`

**Comment by KaSroka** [comment]
@jwhui I've updated the first comment with TODO list. I'm not sure about `wrap_stdint.h` if it's needed or not. All it does after those changes is to include `<stdint.h>`. Some things still have to be done.

**Comment by jwhui** [comment]
@KaSroka, thanks for the continued updates. I think we can remove `src/core/utils/wrap_stdint.h`.

**Comment by KaSroka** [comment]
@jwhui Thanks for the fixes, I was about to fix them now :)

**Comment by jwhui** [comment]
@KaSroka, thanks for this contribution!

**Pull request merged**
