### PR TITLE
Fixes a bad merge from my otInstance declarations change.

### PR DESCRIPTION
**Pull request by nibanks**
I guess ncp_spi.cpp isn't automatically built? This file got messed up in a previous merge but wasn't caught.

### CODE REVIEW

**Comment by darconeous** [comment]
Hmm. We should likely add that to travis, then. On the posix platform it is just a placeholder, but at least it would be a compilation sanity check.

**Comment by darconeous** [comment]
May want to add 985a16b98cecaa26fefa01164795f6ce39fd28d1 to this PR so that travis at least compiles the SPI code. (Travis is testing that commit [here](https://travis-ci.org/darconeous/openthread/builds/160574983))

**Comment by nibanks** [comment]
I added those changes and SPI is building, though I saw it was building on yours as well. Did your build not have the break?

**Comment by jwhui** [comment]
Looks like @darconeous had updated the travis script on top of your change.

**Pull request merged**
