### PR TITLE
Send DTLS-Alert in response to any failures during handshake.

### LINKED ISSUE #622: Commissioning: Handle DTLS handshake failure case due to incorrect PSKd
If Joiner uses incorrect PSKd for DTLS handshake, DTLS server should send _DTLS-Alert_ message with error code 20 (bad record MAC) after receiving _Client Key Exchange_ message from client.
But in current implementation, server ignores it without any response, and handshake will stop after client's four retransmissions.

Certification test 8.1.2 verifies this incorrect PSKd test case.

pcap file:
[incorrect_pskd.pcapng.zip](https://github.com/openthread/openthread/files/479696/incorrect_pskd.pcapng.zip)

### PR DESCRIPTION
**Pull request by jwhui**
Resolves #622.

### CODE REVIEW

**Comment by chshu** [comment]
It seems that this PR does not resolve the issue, I will look into it.

[incorrect_pskd.pcapng.zip](https://github.com/openthread/openthread/files/484090/incorrect_pskd.pcapng.zip)

**Comment by jwhui** [comment]
@chshu, thanks for the review.  I just updated the PR, let me know if it helps.

**Comment by chshu** [comment]
It seems that there is another issue, every DTLS message includes the encrypted DTLS-Alert record now, and DTLS handshake failed even with correct PSKd.
[PR-648.pcapng.zip](https://github.com/openthread/openthread/files/484123/PR-648.pcapng.zip)

I will do more debug work to find the root cause.

**Comment by jwhui** [comment]
@chshu, I made another update to the PR to avoid sending an alert message in response to receiving an alert message.

**Comment by jwhui** [comment]
@chshu, thanks for verifying this PR!

**Pull request merged**
