### PR TITLE
[script] update make-pretty to use clang-tidy-11 and clang-format-11

### PR DESCRIPTION
**Pull request by lmnotran**
This updates `clang-tidy` and `clang-format` to version 11.

[`llvm@9`](https://formulae.brew.sh/formula/llvm@9) is not available to Apple M1 Macs using `brew` 
[`llvm@11`](https://formulae.brew.sh/formula/llvm@11) is available across all platforms in `brew`.
Both `clang-tidy-11` and `clang-format-11` are also available via apt-get for Ubuntu

### CODE REVIEW

**Comment by wgtdkp** [comment]
@lmnotran Thanks for this change! The pretty check is failing, would you help resolve this? (You will need to format the c++ code and upload the new changes)

**Comment by abtink** [comment]
Thank @lmnotran . I think there were some differences between different versions and we may want to double-check its impact (the `pretty` check is failing with clang-11).

It is true that there seems to be no `brew` recipe for llvm9 (not sure why). I did install version 9 directly from https://releases.llvm.org/download.html (I have it running on an M1 mac and also an Ubuntu machine).

**Comment by kghost** [comment]
I'm not sure if I'm asking too much, but clang-11 is also quite old, is it possible to upgrade to `clang-14` which is supported by most modern distributions.

**Comment by jwhui** [comment]
> I'm not sure if I'm asking too much, but clang-11 is also quite old, is it possible to upgrade to `clang-14` which is supported by most modern distributions.

I can take a look at updating clang requirement for pretty check.

**Comment by jwhui** [comment]
Superseded by #8490

**Pull request closed without merging**
