### PR TITLE
Add flash.h to windows build files.

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Comment by jwhui** [comment]
Well, I guess the fix wasn't as intuitive as I thought.  @nibanks, any ideas why `utils/flash.h` cannot be found?

**Comment by nibanks** [comment]
I'm a bit at a loss as to why it is failing as well. Still looking though...

**Comment by nibanks** [comment]
I think it might be that the includes path has the following `;..\..examples\platforms`. It should be `;..\..\examples\platforms`.

If that doesn't fix it, it might be related to the fact you have both `core` and `example\platforms` in the include path, and they both have a sub folder for `utils`. That might be confusing `msbuild`.

**Comment by jwhui** [comment]
@nibanks, the missing `\` was the reason.  Thanks!

**Pull request merged**
