### PR TITLE
Spinel Protocol Documentation Updates

### PR DESCRIPTION
**Pull request by darconeous**
Elaborated on introduction section. Added explanation of how properties are intended to work. Minor fixes to test vectors. Move glossary to the end of the document. Fixed several spelling errors.

This is a part of #492.

### CODE REVIEW

**Comment by darconeous** [comment]
For your convenience, you can preview the HTML version of the document [here](https://rawgit.com/darconeous/openthread/4416cd7/doc/draft-spinel-protocol.html).

You can read the plaintext version [here](https://raw.githubusercontent.com/darconeous/openthread/4416cd7/doc/draft-spinel-protocol.txt).

**Comment by darconeous** [comment]
I am really confused by codecov-io. This change has no code changes, yet it says that code coverage would decrease by 16.76%?

**Comment by darconeous** [comment]
I think this is good to merge ASAP.

**Comment by jwhui** [comment]
On codecov-io, I'm not sure why it decided to pull in `test/` and `third_party/` into the coverage report even though `.codecov.yml` explicitly excludes it.

**Comment by jwhui** [comment]
LGTM 👍

**Pull request merged**
