### PR TITLE
move UpdateChecksum from ip6 to common message

### PR DESCRIPTION
**Pull request by luwannest**
Keep the common functions independently that other apps can use them without linking to the used functions.

### CODE REVIEW

**Comment by jwhui** [comment]
I think it's fine to separate out these functions, but I'm not sure that the `Message` class is the right place to put these checksum functions.  In particular, these checksum functions have nothing to do with `Message` objects.  Can you describe the use case you have in mind for separating these out?

**Comment by luwannest** [comment]
The use case is the dedicated sniffer. It need to link message for the use of message queue. But it does not need to link to Ip that is used by checksum.

**Comment by jwhui** [comment]
What does the sniffer use one's complement checksums for?  Shouldn't it be passing IEEE 802.15.4 frames directly through?

**Comment by luwannest** [comment]
The sniffer does not use checksum. It wanted to leverage the message queue. Then it linked to message. But message uses IP6 's checksum. Sniffer does not need IP6. And I am not sure how many other code needed to be linked, if IP6 was linked.

**Comment by luwannest** [comment]
@jwhui , It may be better that creating a separate header file named checksum.hpp in common folder used to calculate/update checksum. I will submit a patch soon. Do you think that the change is ok or I need to find a better way for this enhancement?

**Comment by jwhui** [comment]
I agree that we should put the checksum function into a separate source file.  For now, ones-complement checksum is only used by the IPv6 code, so I would keep it in `src/core/net` and the `Ip6` namespace.

**Pull request closed without merging**
