### PR TITLE
Enable code coverage reporting, statistics, and history via Codecov.

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Comment by mszczodrak** [comment]
LGTM :+1:

**Comment by turon** [comment]
LGTM :+1:

**Comment by turon** [comment]
Codecov has much nicer, more usable output.  I like the look of the coverage sunburst, but can't say I understand what it is showing yet.  Why is src/ncp not listing coverage of ncp_base.cpp?

**Comment by jwhui** [comment]
@turon, because the PR is still being updated to use codecov.  Hold your horses.

**Comment by turon** [comment]
@jwhui will do - the horses are chomping at the bit in anticipation of this codecov awesomeness!  It's been a long time coming to get cloud visibility of this data and they're thirsty to explore untested fields of red. ;)

**Pull request merged**
