### PR TITLE
[CSL] add extra CSL RECEIVE ahead time due to interop issue

### PR DESCRIPTION
**Pull request by Irving-cl**
Solves issue #8738

### CODE REVIEW

**Comment by Irving-cl** [comment]
Doing some on-device testing.

**Comment by Irving-cl** [comment]
I've built ot-cli-ftd example app on nrf52840dk and verified CSL transmission with a Nest Wifi Router.

@EskoDijk Do you want to first try the case in #8738  before merging this PR?

**Comment by EskoDijk** [comment]
@Irving-cl Thanks, I had a look at the code. I think the below existing code part is still not fully clear:

```
    // CSL receivers would wake up `kCslReceiveTimeAhead` earlier
    // than expected sample window. The value is in usec.
    static constexpr uint32_t kCslReceiveTimeAhead = OPENTHREAD_CONFIG_CSL_RECEIVE_TIME_AHEAD;
```

It mention "CSL receivers would wake up" which may suggest that the receiver is immediately ready to receive. Also the name `kCslReceiveTimeAhead` suggests that the radio is ready to receive `kCslReceiveTimeAhead` us ahead of the start of the expected CSL sampling window which is not the case.  That's because the words "receive" and "ahead" are in there suggesting the receiving starts so many us ahead which is not the case.

Maybe this is more clear:  (I didn't touch the name of the config setting here - better not change that)

```
    // CSL radio is woken up `kCslRampupTimeAhead` earlier than
    // the radio Rx needs to be ready for the actual CSL sample window. The value is in usec.
    static constexpr uint32_t kCslRampupTimeAhead = OPENTHREAD_CONFIG_CSL_RECEIVE_TIME_AHEAD;
```

**Comment by jwhui** [comment]
Superseded by #8743

**Pull request closed without merging**
