### PR TITLE
[docker] add docker file for android check

### PR DESCRIPTION
**Pull request by bukepo**

### CODE REVIEW

**Comment by bukepo** [comment]
@jwhui could you help build openthread/android-trusty from this new Dockerfile, please?

**Comment by jwhui** [comment]
> @jwhui could you help build openthread/android-trusty from this new Dockerfile, please?

@bukepo, built and pushed openthread/android-trusty:latest

**Comment by bukepo** [comment]
Should we merge this PR?

**Comment by jwhui** [comment]
> Should we merge this PR?

I think so. I saw that @librasungirl was tagged for review. Can merge now and update later if needed.

**Pull request merged**
