### PR TITLE
switch travis build to cmake for cc2650 gp712 qpg6095 samr21

### PR DESCRIPTION
**Pull request by FiveDimensions**

### CODE REVIEW

**Comment by jwhui** [comment]
@FiveDimensions, is this PR ready for review? If not, please close this PR for now.

If you are looking to use Travis for testing, you should enable Travis in your own fork (see 
[CONTRIBUTING.md](https://github.com/openthread/openthread/blob/master/CONTRIBUTING.md#initial-setup)). Travis will allocate your own set of build resources in your fork and it will avoid using OpenThread org's build resources during your testing.

**Comment by FiveDimensions** [comment]
@jwhui not yet, plan to add one platform per commit. Sure, will add the rest in next commit.

**Comment by jwhui** [comment]
> @jwhui not yet, plan to add one platform per commit. Sure, will add the rest in next commit.

@FiveDimensions, I'm going to close this PR for now. Please open when you have verified that Travis checks pass and are ready for review. Thanks!

**Comment by FiveDimensions** [comment]
@jwhui Verified on my fork. Could help to reopen this PR?

**Pull request closed without merging**
