### PR TITLE
[tests] use common definition for border router startup delay

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Review by abtink — APPROVED** [review]
Thanks. LGTM. 👍

**Review by wgtdkp — APPROVED** [review]
Thanks! 👍

**Review by simonlingoogle — APPROVED** [review]
LGTM 👍

**Review by librasungirl — APPROVED** [review]
There are `disable_br`/`enable_br` interfaces and used explicitly in some tests, 
e.g. in the `test_nat64_single_border_router.py` and `test_multi_single_border_router.py`, though there are no connectivity validation in these tests, but just wondering do we want to always bundle the unique delay constant per `enable_br()` operation?

**Comment by jwhui** [comment]
> There are `disable_br`/`enable_br` interfaces and used explicitly in some tests, e.g. in the `test_nat64_single_border_router.py` and `test_nat64_multi_border_routers.py`, though there are no connectivity validation in these tests, but just wondering do we want to always bundle the unique delay constant per `enable_br()` operation?

@librasungirl , I updated as suggested in latest push.

**Review by librasungirl — APPROVED** [review]

**Pull request merged**
