### PR TITLE
Update default "CACHE_ENTRIES" and "MAX_CHILDREN" to support required minimum children.

### PR DESCRIPTION
**Pull request by xiaom-GitHub**

### CODE REVIEW

**Comment by xiaom-GitHub** [comment]
To resolve #490 , @jwhui please have a review, and correct me if I miss something to achieve at least 10 children supported.
Router-5.1.7 fails due to another problem, described in [JIRA-TSTBED21](https://threadgroup.atlassian.net/projects/TSTBED/issues/TSTBED-21?filter=allopenissues).

**Comment by jwhui** [comment]
This looks good.  You also need to update `Cert_5_1_07_MaxChildCount.py` for the travis tests to pass.

**Comment by jwhui** [comment]
You will need to add `thread-cert/Cert_5_1_07_MaxChildCount.py` to the `XFAIL_NCP_TESTS` list in `tests/scripts/Makefile.am`

**Comment by xiaom-GitHub** [comment]
@jwhui Thanks much for this remind, I will do that tomorrow morning and give another tryout. :-)

**Comment by jwhui** [comment]
LGMT 👍

**Pull request merged**
