### PR TITLE
[otci] fix command issue after `factoryreset`

### PR DESCRIPTION
**Pull request by simonlingoogle**

### CODE REVIEW

**Comment by gabekassel** [comment]
@simonlingoogle i think i saw a similar behavior with factoryreset hanging the script. do you know when you'll be able to finish this up and merge?

**Comment by simonlingoogle** [comment]
> @simonlingoogle i think i saw a similar behavior with factoryreset hanging the script. do you know when you'll be able to finish this up and merge?

Can this PR fix your issue?

**Comment by gabekassel** [comment]
> > @simonlingoogle i think i saw a similar behavior with factoryreset hanging the script. do you know when you'll be able to finish this up and merge?
> 
> Can this PR fix your issue?

Confirmed, yes it does!

**Comment by simonlingoogle** [comment]
> > > @simonlingoogle i think i saw a similar behavior with factoryreset hanging the script. do you know when you'll be able to finish this up and merge?
> > 
> > 
> > Can this PR fix your issue?
> 
> Confirmed, yes it does!

Could you LGTM if you see no further issue?

**Comment by gabekassel** [comment]
LGTM 👍

**Comment by priyankaCh22** [comment]
LGTM

**Review by priyankaCh22 — APPROVED** [review]
LGTM

**Review by jwhui — APPROVED** [review]

**Pull request merged**
