### PR TITLE
[mbedtls] patch for slow crypto calculations

### PR DESCRIPTION
**Pull request by erja-gp**
This is a proposal to fix https://github.com/openthread/openthread/issues/2176

There were different ways to fix the slow-crypto issue:
1) rely on local timeout to retransmit iso on retransmits from the remote => this might be a spec violation.
2) skip duplicate messages in the rx queue.

This second solution is what I'm attempting to do. It assumes that there are x retransmits from server in the rx queue (where x depends on the speed of the calculations) and it will not trigger local retransmits as long as the sequence number is lower then what we expect for a _real_ retransmit.

Practically: the commissioning patch has been updated to assure that we don't make those unnecessary retransmits.
I.e.:
- when we process the rx queue and there is a retransmit => we will reply to it
- when we process the rx queue and there are duplicate messages (the original which we are processing + a retransmit) => we only reply to one, avoiding duplicate messages.

The updated patch changes the behaviour much earlier (compared to the previous patch) in handshake, and therefor avoids unnecessary duplicate messages.
The patch has a define which should be updated according to duration of the crypto computation.
With these fixes the sniffer log now looks clean.

Note: I did not yet see a way to set these flags from the OpenThread build environment. That makes it impossible to merge as-is.
Any suggestions how to handle this in the OT build ?

Note 2: I was also looking for a way to make part of the original patch conditional (e.g. only include it on the Nordic platform), as this would also solve our issue, albeit with limited duplicate messages being transmitted. But this would also require conditional mbedtls compilation based on flags from the OT build env.

### CODE REVIEW

**Comment by jwhui** [comment]
@erja-gp, thanks for proposing this fix.

On passing platform-specific flags to mbedtls, how about setting them in the platform-specific `mbedtls-config.h` file (e.g. [examples/platforms/nrf52840/crypto/nrf52840-mbedtls-config.h](https://github.com/openthread/openthread/blob/master/examples/platforms/nrf52840/crypto/nrf52840-mbedtls-config.h))?

**Comment by hubertmis** [comment]
@jwhui I'm not mbedtls expert. I'll need some time to understand this PR and compare it with RFC. I estimate I can perform this review in 2 weeks.
Anyway, I performed a smoke test using this PR and it works on nRF52840 well.

**Comment by erja-gp** [comment]
I did a minor cleanup of the patch:
- renamed the defines to MBEDTLS_... , since this issue is not really related to OpenThread code.
- deleted some unnecessary conditions from if statement which I added.
- made sure that by default the fix is disabled!
=> you should now enable it via a platform-specific mbedtls-config.h

Notes:
- I kept the code from the original patch which triggers the mbedtls_ssl_resend , because I think that a) it doesn't harm, and b) it might be needed against devices which rely on the older version of the patch.
- I also kept the modification in mbedtls_ssl_read_record, since this is needed to fast-forward also on the client side, when retransmitted messages are received.

I  also requested in the ARMmbed github group, to verify that the fix which is planned for: https://github.com/ARMmbed/mbedtls/pull/946 would also fix the problem https://github.com/openthread/openthread/issues/2176 which this patch wants to address.

**Comment by erja-gp** [comment]
Correct. But this should exactly match with the retransmitted frames.
Typically you will have (received by the 'slow' joiner from the commissioner):
- hello verify request -> seq 0
- server hello, server key exchange, server Hello Done -> dtls seq 1,2,3
then the retransmit which we want to ignore (as we have been busy with the previous key exchange):
- server hello, server key exchange, server Hello Done -> dtls seq 4,5,6

So by not retransmitting below 6, you would not reply to the last message.
The idea is that you know how long it takes to perform the crypto calculations, and therefor you know exactly how many duplicates (and dtls seq numbers) you will receive, and how many you need to ignore.

If the crypto calculations take > 8s, you expect 1 retransmit, so don't reply untill dtls seq > 6.
If the crypto calculations take > 24s, you expect 2 retransmits, so don't reply untill dtls seq > 9.
etc...
The number '6' is thus not an absolute constant, but something which needs to be adapted depending on the speed of the specific platform.

If your comment is about retransmitting the 'Hello request' in case we missed the 'Hello Verify Request', I have to admit it did not take that into account. Perhaps we should use two limits and ignore only dtls sequence numbers >3 and <=6. But I would need to check the code to see if that scenario passes via the same if statement.

**Comment by hubertmis** [comment]
RFC 6347 4.2.4:

> There are three ways to exit the WAITING state:
> (...)
> 2. The implementation reads a retransmitted flight from the peer: the
      implementation transitions to the SENDING state, where it
      retransmits the flight, resets the retransmit timer, and returns
      to the WAITING state.  The rationale here is that the receipt of a
      duplicate message is the likely result of timer expiry on the peer
      and therefore suggests that part of one's previous flight was
      lost.

It looks that this PR breaks this rule.
I thought you want to prepare for case when we get a few duplicated flights in rx buffer. It may happen when crypto calculations prevents OT from clearing rx buffer. In this case we can retransmit last flight once (instaed of retransmitting once per duplicated flight), but according to RFC we should retransmit it.

**Comment by erja-gp** [comment]
Just to make sure we agree on the behavior. My proposal to update the code such that we get the following behavior:
```
   Joiner                               Commissioner
(1)  |              Client Hello              |
     |--------------------------------------->|
     |                                        |
(2)  |          Hello Verify Request          |
     |<---------------------------------------|
     |                                        |
(3)  |         Client Hello + cookie          |
     |--------------------------------------->|
     |                                        |
(4)  |              Server Hello              |
     |          Server Key Exchange           |
     |           Server Hello Done            |
     |<---------------------------------------|
     |                                        | |
(5)  |              Server Hello              | |  DTLS timeout
     |          Server Key Exchange           | |
     |           Server Hello Done            | v
     |<---------------------------------------| 
     |                                        |
(6)  |          Client Key Exchange           |
     |           Change Cipher Spec           |
     |      Encrypted Handshake Message       |
     |--------------------------------------->|
```
After this no other copy of the ClientKeyExchange is sent, even if we received two copies of the ServerKeyExchange. Do you agree ?

**Comment by hubertmis** [comment]
I agree to proposed behavior, but ale keep in mind failing case:
```
   Joiner                               Commissioner
(1)  |              Client Hello              |
     |--------------------------------------->|
     |                                        |
(2)  |          Hello Verify Request          |
     |<---------------------------------------|
     |                                        |
(3)  |         Client Hello + cookie          |
     |--------------------------------------->|
     |                                        |
(4)  |              Server Hello              |
     |          Server Key Exchange           |
     |           Server Hello Done            |
     |<---------------------------------------|
     |                                        | |
(5)  |              Server Hello              | |  DTLS timeout
     |          Server Key Exchange           | |
     |           Server Hello Done            | v
     |<---------------------------------------| 
     |                                        | |
(6)  |          Client Key Exchange           | |
     |           Change Cipher Spec           | |
     |      Encrypted Handshake Message       | |
     |--------------------------x             | |
     |                                        | |
(7)  |              Server Hello              | |  DTLS timeout
     |          Server Key Exchange           | |
     |           Server Hello Done            | v
     |<---------------------------------------| 
     |                                        |
(8)  |          Client Key Exchange           |
     |           Change Cipher Spec           |
     |      Encrypted Handshake Message       |
     |--------------------------------------->|
```

I'm afraid that this PR will prevent retransmission (8).

**Comment by erja-gp** [comment]
The dtls sequence numbers should keep incrementing. Flight (7) in your diagram should have dtls sequence numbers 7,8,9. Since we only block retransmits up to dtls seq 6, the proposed patch should retransmit flight (8) just like you showed it in the diagram. Although I admit that that behaviour is not tested.

**Comment by hubertmis** [comment]
Right.
And what with following case?
```
   Joiner                               Commissioner
(1)  |              Client Hello              |
     |--------------------------------------->|
     |                                        |
(2)  |          Hello Verify Request          |
     |<---------------------------------------|
     |                                        |
(3)  |         Client Hello + cookie          |
     |--------------------------------------->|
     |                                        | |
(4)  |              Server Hello              | |
     |          Server Key Exchange           | |
     |           Server Hello Done            | |
     |      x---------------------------------| |
     |                                        | |  DTLS timeout
(5)  |         Client Hello + cookie          | v
     |--------------------------------------->| 
     |                                        |
(6)  |              Server Hello              |
     |          Server Key Exchange           |
     |           Server Hello Done            |
     |<---------------------------------------| 
     |                                        |
(7)  |          Client Key Exchange           |
     |           Change Cipher Spec           |
     |      Encrypted Handshake Message       |
     |--------------------------------------->|
```
I think flight (6) should be retransmitted, but it's sequence number of (5) is 2.

**Comment by erja-gp** [comment]
I assumed that this patch would only be enabled on the Joiner (as I've seen it there in my tests), but I see your point. As I mentioned above: perhaps we should use two limits (between 3 and 6), or we could only enable the check after we received the ServerKeyExchange, because if you image e.g. this case:
```
   Joiner                               Commissioner
(1)    |              Client Hello              |
       |--------------------------------------->|
       |                                        |
(2)    |          Hello Verify Request          |
       |<---------------------------------------|
       |                                        |
(3)    |         Client Hello + cookie          |
       |--------------------------------------->|
     | |                                        |
(4)  | |              Server Hello              |
DTLS | |          Server Key Exchange           |
time-| |           Server Hello Done            |
out  | |       x--------------------------------|
     | |                                        |
(5)  v |         Client Hello + cookie          |
       |--------------------------------------->|
       |                                        |
(6)    |              Server Hello              |
       |          Server Key Exchange           |
       |           Server Hello Done            |
       |<---------------------------------------| 
       |                                        | |
(7)    |              Server Hello              | |  DTLS timeout
       |          Server Key Exchange           | |
       |           Server Hello Done            | v
       |<---------------------------------------| 
       |                                        |
(8)    |          Client Key Exchange           |
       |           Change Cipher Spec           |
       |      Encrypted Handshake Message       |
       |--------------------------------------->|
```
Flight (4) has dtls seq 1,2,3 but these get lost.
Flight (6) has dtls seq 4,5,6
After flight (6) the crypto calculations start.
During the calculations we receive flight (7) containing dtls seq 7,8,9.

In this case we should ignore flight (7), i.e. dtls seq 7,8,9.

**Comment by hubertmis** [comment]
I'm not sure if relying on DTLS seq is best approach to this problem. We've seen in discussion above there are many cases, we probably missed something.
Would it be possible to check receive buffer before processing and skip duplicated flights? I think it would be easier to maintain.

**Comment by erja-gp** [comment]
Yes, we can add a condition to make sure that we only drop the "ServerKeyExchange" (and it's friends), but verifying DTLS sequence numbers is needed because they allow us to distinguish between a frame that was received while we were busy, and a possible subsequent frame that was retransmitted by the commissioner because it didn't receive our "ClientKeyExchange". I.e. (copying your diagram):
```
   Joiner                               Commissioner
(1)  |              Client Hello              |
     |--------------------------------------->|
     |                                        |
(2)  |          Hello Verify Request          |
     |<---------------------------------------|
     |                                        |
(3)  |         Client Hello + cookie          |
     |--------------------------------------->|
     |                                        |
(4)  |              Server Hello              |
     |          Server Key Exchange           |
     |           Server Hello Done            |
     |<---------------------------------------|
     |                                        | |
(5)  |              Server Hello              | |  DTLS timeout
     |          Server Key Exchange           | |
     |           Server Hello Done            | v
     |<---------------------------------------| 
     |                                        | |
(6)  |          Client Key Exchange           | |
     |           Change Cipher Spec           | |
     |      Encrypted Handshake Message       | |
     |--------------------------x             | |
     |                                        | |
(7)  |              Server Hello              | |  DTLS timeout
     |          Server Key Exchange           | |
     |           Server Hello Done            | v
     |<---------------------------------------| 
     |                                        |
(8)  |          Client Key Exchange           |
     |           Change Cipher Spec           |
     |      Encrypted Handshake Message       |
     |--------------------------------------->|
```

If we only check for the content, and not for the sequence number, then we would not (re)transmit flight (8) after receiving the retransmitted flight (7).

I think it's not easy to check for duplicates in the rx queue. I assume flight (4) will be removed from the queue when the crypto calculations start, while flight (5) will only enter that queue much later. If you want to do that, we need some time/place where all both flights are present in a single queue.

**Comment by hubertmis** [comment]
I'm still not convinced to relying on sequence number. I've seen devices where ECC calculations took longer than 16 s and there was more than 1 retransmission in rx queue. Each message with greater sequence number.
It looks that we cannot assume compile-time which seq should trigger retransmission and which not. It can vary run-time.

**Comment by erja-gp** [comment]
The intention is to enable the patch on the device where the slow crypto calculations are happening, not to compensate for delays on the remote device.
So, on a specific platform, the calculation time is rather predictable, and then we know upfront how many duplicates we will receive during the (our own) crypto calculations, no ?

**Comment by hubertmis** [comment]
Perhaps, if there was platform-specific configuration how many retransmissions do we expect to receive (both in Joiner and Commissioner roles) and retransmission was prevented only for received 'Server Hello + Server Key Exchange + Server Hello Done' flight in joiner role (not sure which flight one for commissioner role), this approach should be OK

**Comment by erja-gp** [comment]
Ok. I will check when I can spend time to create a new version of the patch.

**Comment by jwhui** [comment]
This is addressed by:
1. https://github.com/ARMmbed/mbedtls/pull/946
2. https://github.com/ARMmbed/mbedtls/pull/1141

**Pull request closed without merging**
