### PR TITLE
[border-router] add test for manual address reachability

### PR DESCRIPTION
**Pull request by edmont**
This PR adds a failing test about manual configured address reachability for a border router.

The issue has shown in Thread 1.2 Certification DUA-TC-20, in the case when the DUT is a Backbone Router. The test is passing for a regular device DUT, as seen with the first ping in the test.

EDIT: Test modified to be valid after the review.

### CODE REVIEW

**Comment by edmont** [comment]
@simonlingoogle @librasungirl @abtink could you help identify the issue?

**Comment by edmont** [comment]
Okay, it seems that the `mExtUnicastAddressPool` is not checked here https://github.com/openthread/openthread/blob/main/src/core/net/ip6.cpp#L1182

I'm still trying to understand the usage of these three methods:
```
bool HasUnicastAddress(const Address &aAddress) const;
bool HasUnicastAddress(const UnicastAddress &aAddress) const;
bool IsUnicastAddressExternal(const UnicastAddress &aAddress) const;
```

**Comment by edmont** [comment]
From the test results it can be seen that both the ping reply and ping request that the BR receives with the GUA as destination are being forwarded to the backbone link.

[test_manual_address_pcaps.zip](https://github.com/openthread/openthread/files/7505858/test_manual_address_pcaps.zip)

**Comment by simonlingoogle** [comment]
@edmont Thanks for disclosing the issue. 

With the current platform network interface implementation and ICMPv6 Echo Handling configuration, BR will pass the Ping Request to the `wpan0` TUN interface to allow kernel to respond with a proper Ping Response. 

However, I found that the kernel may not be properly configured. 

The `wpan0` interface actually does not have the GUA configured, even though `ot-ctl ipaddr` can show the address:

```
root@d65560a7e07e:/app# ot-ctl ipaddr | grep 2002
2002:0:0:0:a:b:c:d
root@d65560a7e07e:/app# ip -6 addr list dev wpan0 | grep 2002
root@d65560a7e07e:/app# 
```

Since the `wpan0` interface is not configured with the GUA, it also does not have the proper route for the GUA prefix:
```
root@d65560a7e07e:/app# ip -6 route list
9100::/64 dev eth0 proto kernel metric 256 pref medium
fd00:db8::/64 dev wpan0 proto kernel metric 256 pref medium
fd88:a175:e438:26bd::/64 dev wpan0 proto kernel metric 256 pref medium
fdbe:ec4:29dd::/64 dev eth0 proto kernel metric 256 expires 1720sec pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev wpan0 proto kernel metric 256 pref medium
default via 9100::1 dev eth0 metric 1024 pref medium
```

I think the issue is that the manually configured addresses are added by `otIp6AddUnicastAddress`, which calls `Netif::AddExternalUnicastAddress`, which actually does not notify the `wpan0` interafce with an address callback. 
This, even though seems odd, is actually intentional according to the current design (please help verify @abtink @bukepo) because a BR with a `wpan0` TUN interface is supposed to use the system command `ip -6 addr add` to add manual addresses rather than `ot-ctl ipaddr add`. 

So, the test passes (verified) if we change the code for adding GUA to be like:
```
br1.bash(f'ip -6 addr add {GUA_1}/64 dev wpan0')
```

---

I think it's debatable if we should call adderss callback when using `ot-ctl ipaddr add` to allow the same address to be added to `wpan0` interface. 
But BRs can use `ip -6 addr add` instead of `ot-ctl ipaddr add` as a short-term fix. 

Thoughts? @bukepo @abtink

**Comment by edmont** [comment]
Thanks for investigating @simonlingoogle . In that case the certification test can be fixed by overriding the address setter method in the BR's THCI:

```
    # Override forceSetSlaac
    @API
    def forceSetSlaac(self, slaacAddress):
        print('forceSetSlaac %s' % slaacAddress)
        self.bash('ip -6 addr add %s/64 dev wpan0' % slaacAddress)
```

As for the general issue, couldn't we just disallow `otIp6AddUnicastAddress` for Border Router builds?

**Comment by abtink** [comment]
> This, even though seems odd, is actually intentional according to the current design (please help verify @abtink @bukepo)

@simonlingoogle , yes, from what I recall this was intentional (callback was added from https://github.com/openthread/openthread/pull/3249). 

Here is a quick summary:
- We have two categories of addresses: 
   - The internal address (the one that OT core itself adds/removes (like mesh-local address), and
   - The external addresses that user (other entities) add/remove. 
- The `otIp6AddressCallback` is invoked only for internal addresses. 
  - I think the idea was that if next layer is adding the address, it already knows about it and no need to invoke the callback to notify it again
  - If I recall, this model helped make certain next layer code (which synced between multiple netifs) easier to write (when you get a callback, you know it is not something that is already on your `wpan` interface and can add/remove it on it).
  - One thing to note is that the `Notifier` events `OT_CHANGED_IP6_ADDRESS_ADDED/REMOVED` are invoked on any type of address, so that can be used to track all changes. 
 
I personally don't have any preference related to this. I guess all models can work and in general we need next layer code to be aware of this and handle syncing of the address/prefixes/routes between the two netifs (the one on OT and the tun `wpan0`).

---------------

> a BR with a wpan0 TUN interface is supposed to use the system command ip -6 addr add to add manual addresses rather than ot-ctl ipaddr add.

This make sense to me and II think this is good way.

-----------

> Couldn't we just disallow `otIp6AddUnicastAddress` for Border Router builds?

I think we want the API to be available on all builds. I expect it to be used by next layer (`ot-br` code) to push the address added on `wpan0` netif down to OT.

**Comment by simonlingoogle** [comment]
> I guess all models can work and in general we need next layer code to be aware of this and handle syncing of the address/prefixes/routes between the two netifs (the one on OT and the tun `wpan0`).

I would suggest to use a different model in which all OT changes are reflected on the `wpan0` interface, but **NOT** map `wpan0` changes back to OT stack. 

The current model is confusing to some extent (which caused this issue in the first place):
- Users would expect IP6 addresses added by `otIp6AddUnicastAddress` (or `ot-ctl ipaddr add`) to be working just fine, however it's not in this case.

The benefit of the current model is that users can apply IPv6 changes to the `wpan0` interface, and expect the corresponding change to happen on the OT stack side. However, the benefits are not that significant:
- We don't have use case to add IPv6 addresses via `ip -6 addr add` on the `wpan0` interface. People usually use `ot-ctl` or CLI since they have been using it for managing OT.
- It's not always possible to add all IPv6 addresses on `wpan0` to OT because OT stack usually have a small limit on the number of unicast/multicast IPv6 addresses  the `ThreadNetif` can have. So, the current model is not guaranteed to work anyway, which makes it even more confusing, because IPv6 addresses added by `ip -6 addr addr` may or may not work. 

Thoughts?

**Comment by simonlingoogle** [comment]
@edmont Please refine the test so that we can merge it. It's covering a case not covered by other tests.

**Comment by edmont** [comment]
@simonlingoogle the test is updated and passing now.

**Review by simonlingoogle — APPROVED** [review]
LGTM 👍 

Thanks

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
