### PR TITLE
Update Thread Management port to 61631.

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Comment by mszczodrak** [comment]
LGTM :+1:

**Comment by librasungirl** [comment]
LGTM 👍

**Comment by luwannest** [comment]
LGTM

**Comment by xiaom-GitHub** [comment]
LGTM

**Comment by GiedriusM** [comment]
Out of curiosity: what is the reason behind this change?

**Comment by jwhui** [comment]
Thread changed the port number because the Thread Group was unable to obtain an allocation from IANA.  At the same time, we wanted to keep Thread's use of CoAP isolated from any applications that may use CoAP.  The particular port value was chosen to allow RFC 6282 UDP port compression.

**Pull request merged**
