### PR TITLE
[cli] `udp bind` doc update to clarify that multicast address cannot be used as argument

### LINKED ISSUE #10315: CLI `udp bind` does not work on a multicast IPv6 address
**Describe the bug** A clear and concise description of what the bug is.

The documentation for `udp bind` mentions an IPv6 address can be provided. However, it doesn't work it seems for multicast IPv6 addresses.  Not clear if this is intentional, or a bug, or just a feature not implemented.

If we agree the feature is not available at this time and it would be some effort to add it, I can as a solution submit a PR on the documentation to mention that multicast is out of scope.

**To Reproduce** Information to reproduce the behavior, including:

In the CLI: 
```
> ipmaddr add ff05::1234
Done
> udp bind ff05::1234 17001
Error 7: InvalidArgs
```

**Expected behavior** A clear and concise description of what you expected to happen.
Would expect 'bind' to succeed. Because multicast IPv6 addresses are not explicitly ruled out.

**Console/log output** If applicable, add console/log output to help explain your problem.
See above.

**Additional context** Add any other context about the problem here.
None

### PR DESCRIPTION
**Pull request by EskoDijk**
close #10315

### CODE REVIEW

**Comment by Vyrastas** [comment]
@EskoDijk This looks fine but it would also be useful to update the CLI documentation that get posted to the openthread.io site as well:

https://github.com/openthread/openthread/blob/main/src/cli/cli_udp.cpp#L73

(That shows up as: https://openthread.io/reference/cli/commands#udp_bind)

Can you add that update here too?

**Comment by EskoDijk** [comment]
@Vyrastas Good suggestion, I've added this also now!

**Review by Vyrastas — CHANGES_REQUESTED** [review]
Just one minor nit

**Comment by EskoDijk** [comment]
@Vyrastas fixed now (by separate web interface commit), thanks.

**Review by Vyrastas — APPROVED** [review]

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
