### PR TITLE
[github-actions] upload test result artifacts

### PR DESCRIPTION
**Pull request by simonlingoogle**
This PR uploads thread-cert test results (e.g. pcap, log) as GitHub Action Artifacts which can be helpful for debugging purposes. 

Test log and PCAPs of these workflows are uploaded:
- [x] Simulation
- [x] Simulation 1.2
- [x] Posix

**Note: artifacts are not shown until the whole workflow is completed.**

### CODE REVIEW

**Comment by FiveDimensions** [comment]
@simonlingoogle  Could you rebase to master since case 6.1.9 merged?  Should we archive the logs as well because there are lots of error info and is helpful to locate?

**Comment by librasungirl** [comment]
@jwhui is there storage cost concern if always upload artifacts as in this PR?

**Comment by simonlingoogle** [comment]
> @jwhui is there storage cost concern if always upload artifacts as in this PR?

@jwhui @librasungirl 

Some information on the storage limit:
- Artifacts automatically expire after 90 days
- We merged about 350 PRs in the last 90 days
- The total size of artifacts of each PR is about 32MB
- The estimated storage requirements of artifacts in 90 days is about 10GB

FYI: [Github Storage Spending Documentation](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#calculating-minute-and-storage-spending)

**Comment by simonlingoogle** [comment]
Changed to only upload artifacts on failures. @FiveDimensions @librasungirl

**Review by librasungirl — APPROVED** [review]

**Review by FiveDimensions — APPROVED** [review]
LGTM

**Comment by simonlingoogle** [comment]
@jwhui Any thought on this PR ?

**Review by jwhui — APPROVED** [review]

**Pull request merged**
