### PR TITLE
[docs] CLI channel

### PR DESCRIPTION
**Pull request by sarah-iot**

### CODE REVIEW

**Review by Vyrastas — COMMENTED** [review]
Header files all LGTM

**Review by abtink — APPROVED** [review]
Thanks. 👍

**Review by Vyrastas — APPROVED** [review]

**Comment by jwhui** [comment]
@sarah-iot , you'll need to increment `OPENTHREAD_API_VERSION` for the `api-version` check to pass.

**Comment by sarah-iot** [comment]
> @sarah-iot , you'll need to increment `OPENTHREAD_API_VERSION` for the `api-version` check to pass.

@jwhui Thanks - done.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
