### PR TITLE
Remove otPlatFlash API's and move settings from core to examples.

### PR DESCRIPTION
**Pull request by pvanhorn**
The otPlatFlash is only needed by the internal otPlatSettings implementations. The otPlatSettings implementation does not belong in core OpenThread source as it is platform specific.  As such, this implementation has been moved to examples and the underpinning flash API's have been moved there as well and have been given a new prefix "utils" in place of "otPlatFlash".

This allows customers to more accurately identify the otPlat API's which they must implement to support OpenThread and to still have access to a implementation of the otPlatSettings API's which is deemed non-trivial.

### CODE REVIEW

**Comment by pvanhorn** [comment]
Honestly, I wasn't sure regarding the proper choice here.  As it is no longer part of the core, it seemed inappropriate to have unit tests for it.  If there is strong demand to keep the unit tests for what is now example code, I would not have a problem with that.

**Comment by nibanks** [comment]
I don't care too much, I just hate to see test code go to waste.

**Comment by jwhui** [comment]
I agree that OpenThread core should not include an implementation of `otPlatSettings*()` APIs.  However, the value of `test_settings.cpp` is that it tests the `otPlatSettings*()` APIs, which may be useful for testing platform-specific implementations of the API.  I think tests for `otPlat*()` APIs would be helpful tools to include with OpenThread.  Thoughts?

**Comment by darconeous** [comment]
The build problem is a long-standing problem with `subdir-objects`. I've got a work-around in 4fee2a3dda8474f95546e.

**Comment by pvanhorn** [comment]
Why was this workaround not necessary for the cc2538 example makefile?

**Comment by darconeous** [comment]
It likely is necessary. I just didn't add it because I couldn't immediately test it. Feel free to apply that work-around to it as well.

The work-around is only necessary when building in a directory that isn't the same directory of the sources, so that is why the CC2538 build doesn't fail.

**Comment by jwhui** [comment]
I'll fix the windows build issues in a separate PR.

**Pull request merged**
