### PR TITLE
[dns64] add recursive DNS64 server

### PR DESCRIPTION
**Pull request by gjc13**
This PR adds a recursive DNS64 server on the border router so that the DNS64 process becomes transperant to the end devices.

The current DNS client with NAT64 implementation sends an A query to the configured DNS server and translates the response to the NAT64 translated IPv6 address in the response handler. This approach brings serveral difficulties for the application layer running on the OpenThread stack:

* Two different DNS servers need to be kept for DNS-SD discovery proxy and common name resolution.
* The NAT64 translation happens in the OpenThread DNS client while applications will typically use the `gethostbyname` function. This function can be provided by lwIP, zephyr or the kernel. These network stacks lack knowlege about the NAT64 prefix in the OpenThread network. The returned addresses are thus not accessible.

To overcome these difficluties, this PR proposes a recursive DNS64 server running together with the discovery delegate.

```
                                                                                             
                                                                                             
                                                                                             
+-------------------+  AAAA queries   +-----------------+ A queries   +---------------------+
|                   |---------------->|                 |------------>|                     |
|    End Device     |                 |  Border Router  |             | Upstream DNS server |
|                   |<----------------|                 |<------------|                     |
+-------------------+  AAAA response  +-----------------+ A response  +---------------------+
                                               |                                             
                                               |                                             
                                               | mDNS quries                                 
                                               v                                             
                                   +------------------------+                                
                                   |                        |                                
                                   |      Backbone LAN      |                                
                                   |                        |                                
                                   +------------------------+                                
                                                                                
```
After the change, the border router will be the only DNS server for the end device. The end device will send AAAA queries and receive corresponding responses both for local devices on the backbone link and the DNS64 addresses translated by the border router. Thus the `gethostbyname` function will work properly.

Main changes include:

* Support backbone interface in the DNS client so that the BR use the DNS client to query the upstream
* Support non-local hostnames in the DNS server
* Support recursive DNS64 server

The border router part of the change is at https://github.com/openthread/ot-br-posix/pull/1298.

### CODE REVIEW

**Comment by gjc13** [comment]
@simonlingoogle @librasungirl I'd like to add CI tests for this change. What's the proper flow and test tool for adding CI for new border router functions?

**Comment by wgtdkp** [comment]
> @simonlingoogle @librasungirl I'd like to add CI tests for this change. What's the proper flow and test tool for adding CI for new border router functions?

@gjc13 Add new test cases to `tests/scripts/thread-cert/border_router`, see https://github.com/openthread/openthread/blob/main/tests/scripts/thread-cert/border_router/README.md for instructions to run border router tests locally.

**Comment by simonlingoogle** [comment]
> * Two different DNS servers need to be kept for DNS-SD discovery proxy and common name resolution.

This can be resolved using `recursive DNS server`?

> * The NAT64 translation happens in the OpenThread DNS client while applications will typically use the `gethostbyname` function. This function can be provided by lwIP, zephyr or the kernel. These network stacks lack knowlege about the NAT64 prefix in the OpenThread network. The returned addresses are thus not accessible.

When the app uses `gethostbyname`, it sends AAAA or A query to the DNS server and can get the corresponding IPv6 or IPv4 address. Application can then translate the IPv4 address to IPv6 address using the NAT64 prefix? 

@gjc13 thoughts?

**Comment by simonlingoogle** [comment]
> As to the `recursive DNS server` currently the border router does not support this option and reports not implemented for all the common name queries. We need to support recursive feature on the border router since it's the only device capable of discovery delegation.

Agree that `recursive DNS server` can be nice to have in OT. 

 I don't see why the recursive DNS server has to be a **DNS64** server. OT DNS server could also redirect queries other than AAAA to public DNS server (e.g. 2001:4860:4860::8888) to resolve dns names like  `google.com`?

**Comment by gjc13** [comment]
> I don't see why the recursive DNS server has to be a **DNS64** server. OT DNS server could also redirect queries other than AAAA to public DNS server (e.g. 2001:4860:4860::8888) to resolve dns names like `google.com`?

The DNS64 server is added for the convenience of end device applications. If we query the NAT64 translated DNS server, the reply will be like:
```
google.com    A        Google IPv4 address
google.com    AAAA     Google IPv6 address
```
Since IPv6 global connectivity is currently not provided we need to use the IPv4 address. As I've described remapping the address manually in the application layer can be troublesome. Lots of application libraries does not allow manually specifying the IP address. They do name resolution in their code. Modifying them and managing those changes can be a challenge.

If we have a DNS64 server on the border router, the reply will be like
```
google.com    AAAA    NAT64 translated IPv6 address
```
When NAT64 is also ready the applications are expected to work out of the box. This will be a desired feature for porting applications on OpenThread.

**Comment by xuyirio** [comment]
Maybe I misunderstood. I thought that the end device applications could use APIs like `otDnsClientResolveIp4Address` to get the NAT64 translated IPv6 address from the A record in the recursive DNS server's response, rather than making the recursive DNS server a DNS64 server. Could you help me understand it?

**Comment by gjc13** [comment]
> Maybe I misunderstood. I thought that the end device applications could use APIs like `otDnsClientResolveIp4Address` to get the NAT64 translated IPv6 address from the A record in the recursive DNS server's response, rather than making the recursive DNS server a DNS64 server. Could you help me understand it?

The device can get the translated address from `otDnsClientResolveIp4Address`. The difficulty happens when we try to port the cloud SDK to Thread devices. They do not use the OpenThread API call to resolve the address. They use common `gethostbyname` instead. As a result they cannot get the translated address.

Forking the cloud SDK and modifying the name resolution logic is possible. However, maitaining or merging such changes is quite painful both for us and our vendors (they may also have their own cloud connection logic). If we have a DNS64 server then everything will work out of the box and this will be a great relief.

**Pull request closed without merging**
