### PR TITLE
[cc2538] fix radio disabled for entropy get

### PR DESCRIPTION
**Pull request by bukepo**
RFCORE_XREG_FRMCTRL0 is not restored after generating random.

### CODE REVIEW

**Comment by bukepo** [comment]
This fixes #3859

**Comment by KaSroka** [comment]
LGTM :+1: 
Thanks for fixing this! I wonder if we should include a change from #3861.

**Comment by librasungirl** [comment]
@KaSroka , 
maybe not appropriate to raise here however I have some questions for `#3818 [entropy] allow for entropy source sharing` which causes the issue this PR tries to fix.

Not sure about other platforms yet, at least cc2538 itself could generate pseudo random number, why we unify all the platforms to use the same Random::NonCrypto in #3818 ?

If we don't want to use the pseudo random number, maybe we don't need to do anything in `cc2538RandomInit()` which mainly prepares for pseudo random number generation?
https://github.com/openthread/openthread/blob/master/examples/platforms/cc2538/entropy.c#L72

**Comment by KaSroka** [comment]
@librasungirl There were few ideas standing behind these changes. First, it's easier for the platform to provide only the entropy source. Many platforms defined their own pseudo random generator or used `rand()` (cc2538 was the only one using something else). Also from a developer point of view, it's easier to distinguish between NonCrypto and Crypto random and decide whether to use them. This would help to avoid the usage of noncryptographic random numbers when cryptographic numbers are needed (at least that's what I hope).

Regarding the cc2538 I have no idea what's this init is doing and if it's connected with RNG or not - that's why I left it here. If it's really not needed then we can remove it.

**Pull request merged**
