### PR TITLE
[build] cmake nrf add output directory for bin and lib

### PR DESCRIPTION
**Pull request by Irving-cl**
This PR makes binaries and libraries generated at specified directory in nrf cmake build. I think putting all the binaries and libraries in one directory is better. (Currently the `build` dir is chaotic.)

Note that currently it only affects cmake build for nrf. Other platforms like simulation are not affected. They are not updated because there are many hard-coded path in our test scripts. Updating them now would certainly break our github actions. I would update them as well later.

This PR is a prerequisite for #6126.

### CODE REVIEW

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1: 
thanks

**Comment by jwhui** [comment]
@Irving-cl , we are in the process of migrating example platforms into separate repos. How about we apply this enhancement to https://github.com/openthread/ot-nrf528xx instead?

**Comment by Irving-cl** [comment]
@jwhui 

Ok, got it.

**Comment by Irving-cl** [comment]
[ot-nrf528xx/#3](https://github.com/openthread/ot-nrf528xx/pull/3)

**Pull request closed without merging**
