### PR TITLE
[mac-filter] change whitelist/blacklist to allowlist/denylist

### PR DESCRIPTION
**Pull request by jwhui**
To promote inclusivity and eliminate any unintentional bias.

### CODE REVIEW

**Review by abtink — APPROVED** [review]
LGTM. Thanks 👍

**Review by Irving-cl — APPROVED** [review]
LGTM👍

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Pull request merged**
