### PR TITLE
[core] add packed version of Clearable and Equatable base classes

### PR DESCRIPTION
**Pull request by abtink**
See #5099 for motivation.

--------
Added a second commit adding workaround for IAR per discussion from https://github.com/openthread/openthread/pull/5099#issuecomment-645540462.

### CODE REVIEW

**Comment by wgtdkp** [comment]
@abtink Sorry I don't understand the problem with existing implementation, could you give some explanations?

**Comment by jwhui** [comment]
> @abtink Sorry I don't understand the problem with existing implementation, could you give some explanations?

@wgtdkp , see #5099 for what motiviated this PR.

**Comment by wgtdkp** [comment]
> > @abtink Sorry I don't understand the problem with existing implementation, could you give some explanations?
> 
> @wgtdkp , see #5099 for what motivated this PR.

@jwhui Thanks!

**Comment by jwhui** [comment]
As mentioned in https://github.com/openthread/openthread/pull/5099#issuecomment-697728993, this is no longer an issue.

**Pull request closed without merging**
