### PR TITLE
[docs] add cert pdf

### PR DESCRIPTION
**Pull request by beriberikix**
Doing this in two parts - this PR uploads the cert PDF. Need it merged before we can link to it directly.

### CODE REVIEW

**Comment by Vyrastas** [comment]
Hmm I don't think I have write access.

**Comment by librasungirl** [comment]
@beriberikix 
Looks like the link below in the pdf is not reachable.
http://www.threadgroup.org/ourtechnology

**Comment by beriberikix** [comment]
@librasungirl ah, good find. I'll let the Thread Group know.

**Comment by beriberikix** [comment]
Closing until we get an updated certificate.

**Comment by beriberikix** [comment]
Updated certificate with the correct url:

[11A001_2017_02_09.pdf](https://github.com/openthread/openthread/files/1180875/11A001_2017_02_09.pdf)

**Pull request closed without merging**
