### PR TITLE
[config] fix config check helper messages

### LINKED ISSUE #4061: Macro update message in openthread-core-config-check.h misleading
For instance we have message:
```
#error "OPENTHREAD_CONFIG_ENABLE_ATTACH_BACKOFF was replaced by OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_JITTER_INTERVAL."
```
However we are in fact using `OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_ENABLE` to replace it. Such misleading messages make it hard and dangerous to update the product configs using OpenThread.

Another weird message is:
```
#error "OPENTHREAD_CONFIG_NUM_SLAAC_ADDRESSES was replaced by NRF_802154_PENDING_EXTENDED_ADDRESSES.
```
NRF_XXX macros should definitely not appear here.

I've not gone through the whole file to check which macro replacement messages are questionable so the above macros are just examples.

### PR DESCRIPTION
**Pull request by abtink**
This commit updates helper error message in `core-config-check.h`
file. It also adds a comment to indicate that error message is
intended as a hint to what the new configuration parameter name
may be.

Resolves #4061.

### CODE REVIEW

**Comment by gjc13** [comment]
```
OPENTHREAD_CONFIG_DISABLE_CCA_ON_LAST_ATTEMPT OPENTHREAD_CONFIG_MAC_DISABLE_CSMA_CA_ON_LAST_ATTEMPT
```
Wrong pair, should be `OPENTHREAD_CONFIG_DISABLE_CSMA_CA_ON_LAST_ATTEMPT`

**Comment by gjc13** [comment]
Missing these macro changes:
```
OPENTHREAD_CONFIG_ENABLE_TIME_SYNC OPENTHREAD_CONFIG_TIME_SYNC_ENABLE
OPENTHREAD_ENABLE_MTD_NETWORK_DIAGNOSTIC OPENTHREAD_CONFIG_TMF_NETWORK_DIAG_MTD_ENABLE
OPENTHREAD_ENABLE_DHCP6_CLIENT OPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE
OPENTHREAD_ENABLE_REFERENCE_DEVICE OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
OPENTHREAD_CONFIG_HEADER_IE_SUPPORT OPENTHREAD_CONFIG_MAC_HEADER_IE_SUPPORT
OPENTHREAD_CONFIG_MAX_JOINER_ENTRIES OPENTHREAD_CONFIG_COMMISSIONER_MAX_JOINER_ENTRIES
OPENTHREAD_CONFIG_NUM_DHCP_PREFIXES OPENTHREAD_CONFIG_DHCP6_SERVER_NUM_PREFIXES
OPENTHREAD_CONFIG_INFORM_PREVIOUS_PARENT_ON_REATTACH OPENTHREAD_CONFIG_MLE_INFORM_PREVIOUS_PARENT_ON_REATTACH
OPENTHREAD_ENABLE_SPINEL_VENDOR_SUPPORT OPENTHREAD_ENABLE_NCP_VENDOR_HOOK
OPENTHREAD_ENABLE_NCP_SPINEL_ENCRYPTER OPENTHREAD_CONFIG_NCP_SPI_ENABLENEL_ENCRYPTER
```

**Comment by abtink** [comment]
Thanks @gjc13 for finding all the config inconsistencies. 

I understand you are trying to update all the internal projects to use the new config model. I added the macro checks mainly to help with update of internal projects (this was done after the main set of commits changing config mode with a script I wrote to try to match old names with new names). My intention was that check macros will be temporary and as safegurad used during transition . _The added list in the config check was not really intended to be a full list or be used as guide of how to update the config params_. Also I would want us to remove the entire check macros list in `openthread-core-config-check.h` after some time (giving time to all projects to transition to new config model). 

Many of the things you found above are beyond not including them in the `"openthread-core-config-check.h"` file. For example,
- We do have `OPENTHREAD_ENABLE_NCP_SPINEL_ENCRYPTER` definition in `configure.ac` but in the `ncp_uart` we seem to be using `OPENTHREAD_CONFIG_NCP_SPI_ENABLENEL_ENCRYPTER`. 
- We seem to have have double definitions: `OPENTHREAD_CONFIG_INFORM_PREVIOUS_PARENT_ON_REATTACH` defined in `config/tmf.h` and `OPENTHREAD_CONFIG_MLE_INFORM_PREVIOUS_PARENT_ON_REATTACH` in `config/mle.h`
- We do have `OPENTHREAD_CONFIG_MAX_JOINER_ENTRIES` defined in `config/joiner.h` which does not seem to be used.
- We still have `OPENTHREAD_CONFIG_NUM_DHCP_PREFIXES` defined in `dhcp6_server.h` (in comments) so the script considred it to be still in use.

I will help fix some of the inconsistencies you found in separate commits/PRs, but since you are taking care of the update of our internal project config files, please feel free to submit fixes directly to OT when you find such issues. Thanks.

**Comment by abtink** [comment]
Submitted https://github.com/openthread/openthread/pull/4068 and https://github.com/openthread/openthread/pull/4069 to address some config issues. 

This commit/PR is also updated to include more checks and adds a disclaimer that the list may not be complete.... I expect the updated PR here to fail travis since we'd need the fix from https://github.com/openthread/openthread/pull/4069 (to remove the duplicate `INFORM_PREVIOUS_PARENT`) before merging this.

**Pull request merged**
