### PR TITLE
[ncp] combine property/command handler declarations and table definitions

### PR DESCRIPTION
**Pull request by abtink**
This commit combines and moves the handler declaration and handler
table definitions in `NcpBase` class for spinel commands and spinel
property get/set/insert/remove operations into common shared files.

----
In current code the list of properties (e.g., all properties that support "get" operation) is repeated in two places:
- In `NcpBase` class definition where the property handler methods are declared.
- In the definition of the handler table (e.g., `mGetPropertyHandlerTable`)  to match the properties with their corresponding handler methods.

The two lists should match and we should ensure that any property which is conditional (requires some `#ifdef`) has the same conditions in the other list.

The new change make it a single list (single source file) which is then used/sahred at both places. While the solution is not ideal (as it uses the `#incldue` pattern from middle of source file), it helps simplify maintaining and adding new properties in future.

### CODE REVIEW

**Comment by bukepo** [comment]
Sorry for the late response. It's great that this PR would save a lot of repeated code, and can absolutely reduce possibility to make mistakes by collecting conditional macros into one place.

As for the `#include` issue you suggested in the description, is it possible that we change the way to define property handlers? Instead of defining them as member functions of `ncp_base`, can we involve a namespace, say `Ncp`, and define `ncp_base` and all property handlers under this namespace? With this change, `ncp_base` would only provide enough public methods(e.g. frame packaging, transmitting and so on) for implementing property handlers. `ncp_base` would also implement a dispatch method to call handlers(probably implementing with `switch` instead of tables). Under this way, we could possibly also put conditional macros at one place(in the dispatch method) but without the `#include` issue. Thoughts? @abtink

**Comment by abtink** [comment]
@bukepo I like your suggestion to simplify the `ncp_base` but I think we may still need the lists in two places. (please let me know if I am missing something).

We need the `#ifdef` in either dispatcher `switch` or lookup table (we considered `switch` but decided for table instead  (the plan for future was to ensure the table keys are sorted so we can do a quick binary search)). 

We can define the handlers as functions under a namespace `Ncp` instead of a class member. Then I guess we need to declare them (as a prototype) in some header file (so we can use them). We can consider declaring all property handlers (without adding the `#ifdef`s in header file). Basically declare all handler functions, but then the definitions/implementations are tied to the `#ifdef` and the function uses are also tied to its `#ifdef`(from either the lookup table of `switch`). The thing is that it's still two places to add and maintain the lists.

**Comment by bukepo** [comment]
@abtink What I suggested just solves what this PR is trying to solve, as you mentioned, it eliminates `#ifdef` in header files, but it cannot eliminates all `#ifdef` in source files. However, it seems this PR cannot remove `#ifdef` in source files either(correct me if I missed anything). I suggest the non-member handlers to,
1. solve the `#include` issue mentioned in this PR's description,
2. make `ncp_base` smaller so that easier to maintain.

I'm not sure if we really need the binary search. Is it frequently to set/get most properties in real products? If not, is it adequate to put some frequently used properties(e.g. STREAM_NET) in the front of the list or the switch.

**Comment by abtink** [comment]
@bukepo my main intention for this change is to avoid having the list repeated in two places.. and have single place to add a new "gettable/settable" spinel property (to help avoid  forgetting to update the lookup table when adding a new property... which I myself have done in more than one occasion... :)... )

I personally don't like the `#include` solution in this PR and would be happy to find an alternate approach to address this.

I do like you idea of having `ncp_base` getter as function in a namespace instead of inside a class... 

Thinking more about this, one approach to have a single list (not needing the function declarations in header file) can be to move the implementation of `HandleCommandPropertyGet()` (the method that goes through the lookup table and maps the property key to its handler and invokes the handler) outsde the `NcpBase` class into the same file where the handlers are defined (so we can have all the handlers defined as `static` scope within the same file)...With https://github.com/openthread/openthread/pull/2045 the properties will be in different files already, so we need to also break the lookup table as well...  It will change the current model but I think it may be workable and possibly/hopefully easier to use...

**Comment by bukepo** [comment]
I understand the motivation of this PR, since I made the same mistake before. :) and I agree your proposed approach.

**Comment by abtink** [comment]
Closing this and try out the new approach...

**Pull request closed without merging**
