### PR TITLE
api: add macros for the channel bit-vector used with `otActiveScan`

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Comment by darconeous** [comment]
I just wanted to point out that by using a 16-bit mask everywhere for the scan mask, we make it more difficult to use OpenThread with the non-2.4GHz versions of 802.15.4.

I think it would be better for us to use a 32-bit mask, without any offset. Then channel 14 would have a mask of `(1<<14)`. Easy to remember and will work with all channels that 802.15.4 is specified for.

**Comment by jwhui** [comment]
That's a fair comment.  But 32 bits is not enough for newer amendments such as IEEE 802.15.4g, which have operating modes that define hundreds of channels within the band.

**Comment by jwhui** [comment]
@darconeous, I updated the type to 32 bits without any offset for now.

**Comment by darconeous** [comment]
The NCP code will also need to be updated to reflect the shift.

**Comment by jwhui** [comment]
@darconeous, updated the NCP code as well.

**Comment by darconeous** [comment]
👍  LGTM

**Pull request merged**
