### PR TITLE
Add DELAY_JOIN_ENT delay before sending JOIN_ENT.ntf message.

### PR DESCRIPTION
**Pull request by hubertmis**

### CODE REVIEW

**Comment by librasungirl** [comment]
The code looks good to me if only one joiner at a time.
what if multiple joiners at the same time?

**Comment by hubertmis** [comment]
@librasungirl Good point. It seems that multiple joiners are not supported at all (single KEK in key manager). I'll provide a simple and hopefully efficient fix for that.

**Comment by librasungirl** [comment]
I could not find any evidence in thread spec for not allowing multiple joiners (Please correct me if I missed something). It might be more reasonable to support multiple joiners here? @jwhui 

As for the single KEK in KeyManager, `kek` could be saved together with `messageInfo` and be set when it is time to send JOIN_ENT.ntf, and be kept for a period enough for JOIN_ENT.rsp, and then next `kek - messageInfo` pair.

Thoughts?

**Comment by hubertmis** [comment]
This PR support simultaneous joining via single joiner router. Just for short period of time the joiner router intentionally drops some frames from a commissioner. Because of lost response, the joiner would retransmit it's request (a few times) and the commissioner would retransmit response that should be processed by the joiner router this time.

If we want to keep a few simultaneous JOIN_ENT transactions, we should provide a few KEK slots in the KeyManager - we don't know in which order JOIN_ENT.rsp messages will arrive. JOIN_ENT transaction is very short (single request - response, one hop). That's why I suggest handling it one by one instead of overcomplicating the code to make this very rare case a little faster.

**Comment by librasungirl** [comment]
It may work however I don't think it is a good idea to intentionally drop some packets and relay on retransmission. Thoughts? @hubertmis  @jwhui

**Comment by hubertmis** [comment]
IMHO generally intentional dropping is a bad approach but in this particular case it simplifies this module a lot. It allows unlimited number of simultaneous Joiners. 
If we don't want to drop this message we should provide finite number of slots. It slot should contain MessageInfo, KEK, time of sending JOIN_ENT message. It is possible to use only 1 KEK in KeyManager if we delay sending JOIN_ENT.req until previous JOIN_ENT transaction ends. But in this case we can support finite number of Joiners. If we supported 2 Joiners and 3rd JOIN_FIN.rsp is received we would drop it anyway due to missing slot.

Most of the time there will be 1 Joiner at the time. That's why I suggest to support 1 Joiner slot for now (already implemented) and use retransmissions in the worst case.

**Comment by librasungirl** [comment]
Personally I think defining a constant `MAX_JOINERS_SIMULTANEOUS` and delay sending JOIN_ENT.req until previous JOIN_ENT transaction ends are more acceptable.

@jwhui, do you have any anything in mind?

**Comment by jwhui** [comment]
How about appending the KEK as metadata into the message buffer in the same way that we append metadata for delayed MLE messages?  This allows us to avoid having a fixed maximum on the number of simultaneous joiners while, at the same time, avoids needing to allocate separate memory just for maintaining the KEK(s).

**Comment by hubertmis** [comment]
I'll have a look how to implement this enhancement. Probably it will be ready in a few days.

**Comment by jwhui** [comment]
@hubertmis, thanks!  Let us know your thoughts.

**Comment by hubertmis** [comment]
I've modified this PR according to your suggestions. It seems that it works as expected.

**Pull request merged**
