### PR TITLE
Reintroduction of `.gitattributes`

### PR DESCRIPTION
**Pull request by darconeous**
`.gitattributes` was originally introduced via pull request #473. The file was temporarily reverted in pull request #594. This commit reintroduces the change with the appropriate adjustments to the internal git representations for these files.

### CODE REVIEW

**Comment by nibanks** [comment]
What 'complaints' are you getting? Does this PR just change line endings? If so, my understanding of the .gitattribute file was to make that unnecessary and automatic.

**Comment by darconeous** [comment]
This should be merged as soon as integration is complete, preferably before any other commits are merged.

**Comment by darconeous** [comment]
heh, well, it's not that easy. Git stores all text files with unix endings. If you say that a file should have CRLF endings, then it still stores those files in the repository with unix endings---git just automatically does conversions to/from CRLF when you checkout.

So all of these files already have CRLF in the git repository. Changing them to have the CRLF attribute means that, in the actual back end, all of those CRLF endings need to be converted to be unix format. Otherwise you get tons of stuff in your "git status" that says you have changed it but you haven't really.

**Comment by darconeous** [comment]
This is a rather subtle a complicated thing. This commit doesn't actually change the files at all, It changes their internal representation. Previously they were effectively stored as binary files. If the file had CRLF endings, they were saved to the history. If it had only LF endings or even mixed line endings, those were saved too. By setting CRLF enforcement, you are explicitly telling git "Hey, this is a text file, and it is special because it always has CRLF endings". Internally, git will represent the file diffs using unix line endings, and it will simply convert to and from CRLF upon commit and checkout, transparently.

Because there are still CRLF endings in the history, that needs to be corrected.

**Comment by mszczodrak** [comment]
LGTM 👍

**Comment by darconeous** [comment]
hold off merge.

**Comment by darconeous** [comment]
Oh, nevermind, I scared myself when I saw a `*` in my command prompt, turns out it was something I added. Haha.

**Comment by darconeous** [comment]
Ya know it might make sense to revert the change to .gitattributes first, and then commit a change with this and the new .gitattributes together.

**Comment by darconeous** [comment]
I'm going to investigate that, because I'm noticing this commit will lead to some difficulty. Closing temporarily to make sure no one merges it.

**Comment by darconeous** [comment]
Once #594 is merged, we can merge this commit and it will make everything right in one flail swoop.

**Pull request merged**
