### PR TITLE
[harness-simulation] fix `build_docker_image.sh` error

### PR DESCRIPTION
**Pull request by jcdong98**
Fix https://github.com/openthread/openthread/issues/8068 that building docker image fails.

### CODE REVIEW

**Review by simonlingoogle — APPROVED** [review]
LGTM 👍

**Comment by simonlingoogle** [comment]
@shouvik-grl  Please help verify if your issue can be resolved by this PR. Thanks.

**Comment by shouvik-grl** [comment]
Hi @simonlingoogle @jcdong98 

This with this PR the docker image building is successful but during running the simulator getting this error:
DockerStart Error


Getting the Error in both (RaspberryPi + raspbian OS  as well as WSL + Ubuntu 22.04)

**Comment by simonlingoogle** [comment]
> Hi @simonlingoogle @jcdong98
> 
> With this PR the docker image building is successful but during running the simulator getting this error: DockerStart Error
> 
> Getting the Error in both (RaspberryPi + raspbian OS as well as WSL + Ubuntu 22.04)

Maybe there is leaking OTBR Docker instance that has taken up the name `otbr_7`. 
@shouvik-grl Could you check the outout of command: `sudo docker ps`?

**Comment by jcdong98** [comment]
> Hi @simonlingoogle @jcdong98
> 
> With this PR the docker image building is successful but during running the simulator getting this error: DockerStart Error
> 
> Getting the Error in both (RaspberryPi + raspbian OS as well as WSL + Ubuntu 22.04)

It seems that I forgot to execute `sudo modprobe ip6table_filter` in the script. OTBR firewall scripts create rules inside the Docker container. Run `modprobe` to load the kernel modules for `iptables`. `modprobe` needs to be run before starting the Docker container. I will add the command to the script later.

**Comment by simonlingoogle** [comment]
> > Hi @simonlingoogle @jcdong98
> > With this PR the docker image building is successful but during running the simulator getting this error: DockerStart Error
> > Getting the Error in both (RaspberryPi + raspbian OS as well as WSL + Ubuntu 22.04)
> 
> It seems that I forgot to execute `sudo modprobe ip6table_filter` in the script. OTBR firewall scripts create rules inside the Docker container. Run `modprobe` to load the kernel modules for `iptables`. `modprobe` needs to be run before starting the Docker container. I will add the command to the script later.

Thanks for catching the issue.

**Comment by shouvik-grl** [comment]
> > Hi @simonlingoogle @jcdong98
> > With this PR the docker image building is successful but during running the simulator getting this error: DockerStart Error
> > Getting the Error in both (RaspberryPi + raspbian OS as well as WSL + Ubuntu 22.04)
> 
> Maybe there is leaking OTBR Docker instance that has taken up the name `otbr_7`. @shouvik-grl Could you check the output of command: `sudo docker ps`?
> 
> @jcdong98 How do we make sure all OTBR Docker containers are properly shut down and removed when `launch_testbed.py` exits?

`docker ps` not listed any container
dpsA

**Comment by jcdong98** [comment]
> How do we make sure all OTBR Docker containers are properly shut down and removed when `launch_testbed.py` exits?

@simonlingoogle If everything goes well, all OTBR Docker containers should be properly shut down and removed in `launch_testbed.py` when it receives SIGINT or SIGTERM, which is probably triggered by pressing `Ctrl+C` or using `kill` command.

**Comment by shouvik-grl** [comment]
With this PR, now the above mentioned issues are solved (RaspberryPi + Raspbian OS)

Thanks @jcdong98 and @simonlingoogle for your support.

We are working on the further processes.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
