### PR TITLE
spi-hdlc-adapter: Don't call `syslog()` or `fprintf()` from signal handlers

### PR DESCRIPTION
**Pull request by darconeous**
`syslog()` and `fprintf()` are not async-signal-safe. They can (and
do) cause deadlocks under various circumstances.

This change replaces the calls to these functions with calls to
`write()`. It also adds a watchdog of sorts to the `signal_critical()`
handler to make sure that even if we call some functions that
are not async-signal-safe that we will at least terminate eventually.

### CODE REVIEW

**Comment by abtink** [comment]
LGTM :+1:

**Comment by darconeous** [comment]
Um.... What the hell. Travis is complaining about me not using the return value from a call to `write()` which I am explicitly ignoring because I know what I'm doing and I really don't care what the return value is:

```
    // Can't use syslog() because it isn't async signal safe.
    // So we write to stderr
    (void)write(STDERR_FILENO, message, sizeof(message)-1);
```

Honestly, it feels like `-Werror=unused-result` is broken in this circumstance.

Thoughts?

**Comment by darconeous** [comment]
Nevermind, I'm now using a trick I learned from @mszczodrak a while back.

**Comment by mszczodrak** [comment]
LGTM :+1:

**Comment by jwhui** [comment]
LGTM :+1:

**Pull request merged**
