### PR TITLE
[est-client] adding EST client functions with CLI example

### PR DESCRIPTION
**Pull request by AuSchell**
Enrollment over Secure Transport (EST) client module with CoAP Secure according to [RFC7030](https://tools.ietf.org/html/rfc7030) and [draft-ietf-ace-coap-est-12](https://tools.ietf.org/html/draft-ietf-ace-coap-est-12). This PR adds the following functionalities:
- Generating a 256-bit elliptic curve key pair in openthread crypto using mbedtls.
- Simple enrollment over coaps
- Simple reenrollement over coaps
- CLI commands for connecting a client to an EST server with DTLS, simple enrollment and reenrollment

not yet implemented:
- Requesting CSR attributes
- Requesting server-side key generation
- Requesting CA certificate from server

The IP of an EST server, an EC keypair and the corresponding X509 public key certificate are also provided. If no IP is specified using the "est connect" CLI command, the client connects to the aforementioned server.

### CODE REVIEW

**Comment by ChrIgiSta** [comment]
> So there's good news and bad news.
> 
> +1 The good news is that everyone that needs to sign a CLA (the pull request submitter and all commit authors) have done so. Everything is all good there.
> 
> confused The bad news is that it appears that one or more commits were authored or co-authored by someone other than the pull request submitter. We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that here in the pull request.
> 
> _Note to project maintainer: This is a terminal state, meaning the `cla/google` commit status will not change from this state. It's up to you to confirm consent of all the commit author(s), set the `cla` label to `yes` (if enabled on your project), and then merge this pull request when appropriate._
> 
> information_source **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fopenthread%2Fopenthread%2Fpull%2F3982) for more info**.

I confirm.
I agree with this PR.

**Comment by jwhui** [comment]
@AuSchell @ChrIgiSta, thank you for submitting this contribution!

As mentioned in #3990, Thread 1.2 Commercial Extensions employs ANIMA/BRSKI/EST and the protocol specification was directly influenced by Fairhair - I noted your [paper](https://digitalcollection.zhaw.ch/handle/11475/13236) that mentions Fairhair. It would be great to see if we could align your efforts with the Thread 1.2 Commercial Extension effort. I also noted that your organization is applying for Thread membership - have you been able to complete the application?

**Comment by AuSchell** [comment]
@jwhui, thank you for your answer.

We are now an academic member of the Thread Group, so I have now access to the Thread specs. We are very interest in combining our efforts with other working on implementing CCM. Are you at the Thread Meeting next week hosted by Siemens in Zug, Switzerland? They are our client in this project. I myself will not be there, but Christian Honegger, who is our contatc in Siemens, will be. Maybe you could introduce him to other collaborators.

**Comment by jwhui** [comment]
This will be combined into the Thread 1.2 effort.

**Pull request closed without merging**
