### PR TITLE
[border-router] enhance on-link prefix check

### PR DESCRIPTION
**Pull request by wgtdkp**
This commit applies on-link validations described by https://www.ietf.org/archive/id/draft-lemon-stub-networks-02.html#section-3.1.1.

### CODE REVIEW

**Review by abtink — COMMENTED** [review]
LGTM. Thanks. 👍

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Comment by wgtdkp** [comment]
> LGTM. Thanks. 👍

@abtink  You didn't approve the PR actually. 😄

**Review by abtink — APPROVED** [review]
(Other than Jonathan's suggestion) LGTM. Thanks 👍

**Review by jwhui — APPROVED** [review]

**Pull request merged**
