### PR TITLE
Add arm-gcc54 to travis and -Wno-c++14-compat to CXXFLAGS.

### LINKED ISSUE #825: Failed to build OpenThread with the newer toolchain
It fails when building latest OpenThread with a newer toolchain, for example: [5-2016-q2-update](https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update):

Build steps:
```
./bootstrap
make -f example/Makefile-cc2538
```

Build failure logs:

```
In file included from /home/chenshu/code/openthread/examples/../src/core/openthread.cpp:47:0:
/home/chenshu/code/openthread/examples/../src/core/common/new.hpp:42:15: error: 'void operator delete(void*, size_t)' is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Werror=c++14-compat]
 void OT_CDECL operator delete(void *, size_t) throw();
               ^
In file included from /home/chenshu/code/openthread/examples/../src/core/net/ip6.cpp:38:0:
/home/chenshu/code/openthread/examples/../src/core/common/new.hpp:42:15: error: 'void operator delete(void*, size_t)' is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Werror=c++14-compat]
 void OT_CDECL operator delete(void *, size_t) throw();
               ^
/home/chenshu/code/openthread/examples/../src/core/openthread.cpp:66:15: error: 'void operator delete(void*, size_t)' is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Werror=c++14-compat]
 void OT_CDECL operator delete(void *, size_t) throw() { }
```

We could build CC2538 platform with an older toolchain, for example: [4.9-2015-q3-update](https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update).

### PR DESCRIPTION
**Pull request by jwhui**
Resolves #825.

### CODE REVIEW

**Comment by jwhui** [comment]
@wbober, @LuDuda, @nibanks I think this is a cleaner solution to addressing the sized delete issue.  This avoids introducing Windows-specific preprocessor checks into core.

**Comment by bukepo** [comment]
LGTM👍

**Comment by LuDuda** [comment]
LGTM :+1:  I have no errors during compilation using this patch.

**Comment by wbober** [comment]
:hand: Unfortunately this doesn't fix #826.

**Comment by jwhui** [comment]
@wbober, gcc6 sets the default mode for C++ to `-std=gnu++14`.  Couple questions:

1. Are you OK with setting the C++ mode to an earlier version?
2. What features of gcc6 interest you - gcc6 is relatively bleeding edge :)

**Comment by wbober** [comment]
@jwhui, I see. That explains the issue :)

Ad1) Yes, I'm fine.
Ad2) None in particular. I'm simply using ArchLinux and that's the reason I have gcc6.

**Comment by jwhui** [comment]
@wbober, thanks.  I'll update this PR to add gcc6 to travis soon.

**Comment by jwhui** [comment]
I'm going to merge this first then submit a separate PR for gcc6.

**Pull request merged**
