### PR TITLE
[link-raw] set receive done callback when enabled

### PR DESCRIPTION
**Pull request by bukepo**
This fixes openthread/ot-esp32#6.

### CODE REVIEW

**Comment by bukepo** [comment]
This also fixes the scan issue in https://groups.google.com/g/openthread-users/c/rfMMH178CvI/m/BrvcRal9BgAJ

**Comment by bukepo** [comment]
Should be introduced by #5068, because transmit will not call receive now if the radio supports.

**Comment by jwhui** [comment]
> Should be introduced by #5068, because transmit will not call receive now if the radio supports.

Can we add a continuous integration check to make sure the scan function does not break in the future?

**Comment by bukepo** [comment]
> > Should be introduced by #5068, because transmit will not call receive now if the radio supports.
> 
> Can we add a continuous integration check to make sure the scan function does not break in the future?

Added the check as an expect test.

**Pull request merged**
