### PR TITLE
ncp: Added initial MeshCoP commands.

### PR DESCRIPTION
**Pull request by turon**
Initial Spinel additions for Cert_8_1 Commissioning tests

    Added new role properties
      Joiner: enabled, credential, url
      Commissioner: enabled, and joiner list.

    CLI commands are as before, but otApi was split to better model
    property paradigm of Spinel.

    Example:
      joiner start [pskd] [url]
        now maps to three operations: set credential, set url, and set enabled

    Includes some spinel-cli cleanup:
        - Fixes to 'U' UTF8 handling.
        - Fixes to 'D' DATA types such as masterkey
        - handle_property utility can now be passed above types

    Passing first Commissioning tests: 8_1_01 and 8_1_02.

    Also updated spinel to use proper terminology for UNSECURED packets.

### CODE REVIEW

**Comment by jwhui** [comment]
I glanced at this PR.  Some high-level comments:

1. We should not be trying to align the OpenThread APIs to mirror Spinel's property-based design.  For example, see the scan operation, as one example.
2. I'm not convinced that the Commissioner role should live in the NCP.  If it turns out that the Commissioner role should live in the NCP,  there is a lot more to sort out and I'd like to see a full design in mind rather than taking a piecemeal approach.
3. Also, what do you have against ```insecure```?  ```unsecured``` is a past participle, which doesn't make sense for outgoing packets.  At the same time, ```unsecure``` is not a recognized word.

**Comment by turon** [comment]
Hi @jwhui,

1. For the Native Commissioner API, I think we want to move to a Joiner List approach so we can handle cases beyond a single Joiner.  There would need to be a way to specify Joiner IIDs and multiplex multiple DTLS server sessions.  

Regarding the Joiner API, I'm indifferent on start/stop vs. enable, though pausing the Joiner role with preserved settings allows for coarse power management.  Longer term, I think we'd want some indications to the higher layer to signal candidate networks found and bloom filter hits to allow better management of hunting, and allow Joiner back-off decisions so a device can power management when no candidate networks are present.

2. To the extent the API for the case of an SoC with display is progressing forward with a good plan in mind, adding corresponding NCP hooks is fairly trivial.  We also get the benefit of passing the functional test suite when we preserve some form of a 1:1 mapping.

3. Ok, I somehow convinced myself "unsecured" is the proper term, but can revert that part.

in·se·cure
ˌinsəˈkyo͝or/
2. (of a thing) not firm or set; unsafe.

un·se·cured
ˌənsəˈkyo͝ord/
adjective
2. not made secure or safe.

**Comment by jwhui** [comment]
> 1) For the Native Commissioner API, I think we want to move to a Joiner List approach so we can handle cases beyond a single Joiner. The protocol is designed to be scalable and allow commissioning multiple Joiners in parallel. To handle that there would need to be a way to specify Joiner IIDs and multiplex multiple DTLS server sessions. Perhaps handling those more complex cases is beyond scope or low priority, but that is the thinking for the API change.

Handling multiple DTLS sessions simultaneously in a resource-constrained device is not going to provide a good user experience.  I expect more complex cases scenarios to involve more capable platforms that have the ability to use an alternate implementation of the commissioner.

> Regarding the Joiner API, I'm indifferent on start/stop vs. enable, though pausing the Joiner role with preserved settings allows for coarse power management. Longer term, I think we'd want some indications to the higher layer to signal candidate networks found and bloom filter hits to allow better management of hunting, and allow Joiner back-off decisions so a device can power management when no candidate networks are present.

The callback already exists using the `otDiscover()` API.  I plan to enhance the joiner API to allow passing an `otActiveScanResult` as well.

> 2) To the extent the API for the case of an SoC with display is progressing forward with a good plan in mind, adding corresponding NCP hooks is fairly trivial. We also get the benefit of passing the functional test suite when we preserve some form of a 1:1 mapping.

Continuously updating Spinel just to expose the same functionality as CLI is short-sighted and doesn't recognize architectural differences between the single processor and NCP modes of operation.

**Comment by turon** [comment]
Withdrawing this PR until Border Agent proxy method for offloading native commissioner to host processor is in place.

**Pull request closed without merging**
