### PR TITLE
[network-data] remove all matching entries from `RemoveRloc` methods

### PR DESCRIPTION
**Pull request by abtink**
This commit makes changes to ensure the `Leader::RemoveRloc` methods
remove all matching entries from a `BorderRouterTlv` or `HasRouteTlv`
It adds new methods to `BorderRouterTlv` and `HasRouteTlv` to get the
first entry or last entry and allow an easier way to iterate over all
the entries.
This commit also adds a new helper method `RlocMatch()` to simplify
the comparison of RLOC16 values (exact match vs router id match).

----
PR https://github.com/openthread/openthread/pull/2905 helped fix the issue to clean a child-added network data when its parent is removed. This PR address a related issue where if there were multiple matching entries, only the first one would have been removed (we would `break` from the loop going over entries upon finding a match).

### CODE REVIEW

**Comment by abtink** [comment]
This fixes how we remove multiple "_matching_" entries. It's correct that if we do an **exact** match, there should be only one entry per RLOC. This issue applies when the relaxed definition of matching (i.e., `aExactMatch=false` where router ID is checked) is used. 

A parent router node and its child can both register the same on-mesh prefix. If the parent is gone, when we perform a remove we should ensure to remove both entries (which would be under the same `BorderRouterTLv`). In the original code, after a match we would `break` and not continue to seach and would not remove the child entry.

I have a pending `toranj` test-case creating this situation which currently fails on master but passes with this change. Will submit it as a new PR after some code clean up.

**Comment by jwhui** [comment]
Thanks for the clarification - that makes sense now. I think we could do a better job clarifying "Match". For example, Router ID vs. RLOC16.

I also think we should transition to a policy where tests are included in to the PR to help demonstrate that the PR actually fixes the bug.

Thoughts?

**Comment by abtink** [comment]
I agree. Suggest replacing the `bool aExactMatch` with an enum `MatchMode` definition (say `kRloc16Match, kRouterIdMatch`) and change all the code to use this instead. Perhaps a future improvement.

I like the policy of requiring tests along with the change. It'd be good to keep commits separate (to help with cherry-picking of fix without the test).

Will clean up the test and add it to this PR.

**Comment by abtink** [comment]
Pushed a new commit on this PR which adds a `toranj` test case:

```
 Network topology

   r1 ----- r2
            |
            |
            c2 (sleepy)
```
Test covers the following steps:
- Every node adds a unique on-mesh prefix.
- Every node also adds a common on-mesh prefix (with different flags).
- Verify that all the unique and common prefixes are present on all nodes are associated with correct RLOC16.
- Remove `r2` from network (which removes `c2` as well) from Thread partition created by `r1`.
- Verify that all on-mesh prefixes added by `r2` or `c2` (unique and common) are removed on `r1`.

**Pull request merged**
