### PR TITLE
[mle] remove secure data request mode bit

### PR DESCRIPTION
**Pull request by jwhui**
- Always set to 1 on transmission.
- Always ignore on reception.

Resolves #5559

### CODE REVIEW

**Review by librasungirl — APPROVED** [review]
LGTM 👍

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Review by abtink — APPROVED** [review]
LGTM. Thanks for doing this. 👍

**Pull request merged**
