### PR TITLE
[radio] add proprietary radio support

### PR DESCRIPTION
**Pull request by schinchani**
In this PR, I have added single-band proprietary radio support for OpenThread. This feature will enable users to configure OpenThread stack with proprietary radio parameters and use a PHY as defined by the Platform.

More specifically, I have:
1. Introduced the following platform configuration options:
- OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_SUPPORT
- OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN
- OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX
- OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK
- OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE

2. Updated the radio and meshcop tlv implementation to incorporate the proprietary radio configurations
3. Updated the network diagnostics code to support channel page mask value up to 32.

### CODE REVIEW

**Comment by schinchani** [comment]
Hi @jwhui,  Any initial thoughts on this enhancement request?

**Comment by romacdon** [comment]
@jwhui / @abtink - any thoughts on this change?

**Review by abtink — APPROVED** [review]
LGTM. 👍

**Review by jwhui — APPROVED** [review]
Looks great! 👍🏼

**Comment by jwhui** [comment]
@schinchani , can you rebase this on the latest main branch to get the CI tests to pass?

**Comment by schinchani** [comment]
> @schinchani , can you rebase this on the latest main branch to get the CI tests to pass?

Hi @jwhui ,

I rebased my feature branch on the latest main, however, that applied all the latest changes to my feature branch, making me wonder if I should have done a simple merge from the latest main to my branch instead (that I usually do)?

What is the recommended workflow? Hopefully, I haven't messed up my feature branch.

**Comment by jwhui** [comment]
> What is the recommended workflow? Hopefully, I haven't messed up my feature branch.

I typically do the following:
```
git checkout <branch>
git remote add upstream git@github.com:openthread/openthread.git
git fetch upstream main
git rebase upstream/main
```

**Comment by schinchani** [comment]
> > What is the recommended workflow? Hopefully, I haven't messed up my feature branch.
> 
> I typically do the following:
> 
> ```
> git checkout <branch>
> git remote add upstream git@github.com:openthread/openthread.git
> git fetch upstream main
> git rebase upstream/main
> ```

Yeah, That's exactly what I did. git prompted that my branch had diverged, so it asked me to do a git pull, followed by a git push.

**Comment by jwhui** [comment]
> > I typically do the following:
> > ```
> > git checkout <branch>
> > git remote add upstream git@github.com:openthread/openthread.git
> > git fetch upstream main
> > git rebase upstream/main
> > ```
> 
> Yeah, That's exactly what I did. git prompted that my branch had diverged, so it asked me to do a git pull, followed by a git push.

It doesn't look that way from your branch. Rebase should take your set of commits and put them after upstream/main. Instead, your branch has the commits from upstream/main after your commits.

To recover, you can do the following:
```
git checkout staging/proprietary_radio_support
git reset 6d943a0eca5b956621c80576e02181f886540a71
git checkout -- .
git clean -xfd
git remote add upstream git@github.com:openthread/openthread.git
git fetch upstream main
git rebase upstream/main
```

**Comment by schinchani** [comment]
> > > I typically do the following:
> > > ```
> > > git checkout <branch>
> > > git remote add upstream git@github.com:openthread/openthread.git
> > > git fetch upstream main
> > > git rebase upstream/main
> > > ```
> > 
> > 
> > Yeah, That's exactly what I did. git prompted that my branch had diverged, so it asked me to do a git pull, followed by a git push.
> 
> It doesn't look that way from your branch. Rebase should take your set of commits and put them after upstream/main. Instead, your branch has the commits from upstream/main after your commits.
> 
> To recover, you can do the following:
> 
> ```
> git checkout staging/proprietary_radio_support
> git reset 6d943a0eca5b956621c80576e02181f886540a71
> git checkout -- .
> git clean -xfd
> git remote add upstream git@github.com:openthread/openthread.git
> git fetch upstream main
> git rebase upstream/main
> ```

Thank you @jwhui . I tried to recover using the exact commands you posted. All commands executed fine.

**Comment by jwhui** [comment]
> Thank you @jwhui . I tried to recover using the exact commands you posted. All commands executed fine. However, when i did a git status at the end, it gave me the following message:
> 
> ```
> sachinch@mac0014055:~/siliconlabs/openthread$ git s
> On branch staging/proprietary_radio_support
> Your branch and 'origin/staging/proprietary_radio_support' have diverged,
> and have 25 and 25 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)
> 
> nothing to commit, working tree clean
> ```

Yes, the divergence is expected because you rebased your local branch, which inserts commits into the middle of your commit history. You simply need to force-push your branch since it is not longer a simple fast forward.
```
git push origin staging/proprietary_radio_support --force
```

**Comment by schinchani** [comment]
@jwhui  - while waiting for your response, I actually updated the siliconlabs/openthread main to latest, and merged it into my feature branch, which got my changes on top of it. I saw the command  then, and that returned:

```
sachinch@mac0014055:~/siliconlabs/openthread$ git push origin staging/proprietary_radio_support --force
Everything up-to-date
sachinch@mac0014055:~/siliconlabs/openthread$
```
I think, the branch should be in good shape now. Can you please confirm?

**Comment by schinchani** [comment]
Thank you!

**Pull request merged**
