### PR TITLE
[cli] fix ifdef guard

### PR DESCRIPTION
**Pull request by Irving-cl**

### CODE REVIEW

**Comment by superwhd** [comment]
Could you also fix the comment of `Utils`'s constructor?
```
    /**
     * Initializes the `Output` object.
     *
     * @param[in] aInstance           A pointer to OpenThread instance.
     * @param[in] aImplementer        An `OutputImplementer`.
     *
     */
    Utils(otInstance *aInstance, OutputImplementer &aImplementer)
```

**Comment by Irving-cl** [comment]
> Could you also fix the comment of `Utils`'s constructor?
> 
> ```
>     /**
>      * Initializes the `Output` object.
>      *
>      * @param[in] aInstance           A pointer to OpenThread instance.
>      * @param[in] aImplementer        An `OutputImplementer`.
>      *
>      */
>     Utils(otInstance *aInstance, OutputImplementer &aImplementer)
> ```

@superwhd Thanks! Updated.

**Review by superwhd — APPROVED** [review]
LGTM 👍

**Review by abtink — APPROVED** [review]
👍

**Review by jwhui — APPROVED** [review]

**Pull request merged**
