### PR TITLE
[csl] ignore zero valued CSL IE period

### PR DESCRIPTION
**Pull request by edmont**
Ignore a CSL IE with period set to 0.

Accepting it would eventually lead to a division by 0 fault in `CslTxScheduler::GetNextCslTransmissionDelay`.

### CODE REVIEW

**Review by Irving-cl — APPROVED** [review]
LGTM 👍 

I'm thinking we can even set a minimum value for CSL period. Values like 1 or 2 symbols are not practical and may be used to attack the router.

**Comment by edmont** [comment]
> I'm thinking we can even set a minimum value for CSL period. Values like 1 or 2 symbols are not practical and may be used to attack the router.

I agree. Given that today's minimum CSL Transmitter to CSL Receiver frame it's probably a Child Supervision message (empty data frame), its length being 25 octets (counting preamble), the maximum transmission rate would be 25*32 = 800 us --> 5 times 160 us (assuming no ack requested). So what about setting this minimum period?

**Comment by edmont** [comment]
Okay, we already have a configurable `kMinCslPeriod` defaulting 10 symbols.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
