### PR TITLE
[docs] add source for BeagleBone Black guide

### PR DESCRIPTION
**Pull request by Vyrastas**
The end formatting on openthread.io will be different (many step lists removed and some text shifted around).  Once this is in, @srickardti you can update it for your BBB changes.

Also updated the Style Guide to add a Contributor tag section.

### CODE REVIEW

**Comment by jwhui** [comment]
@Vyrastas , the pretty check is failing. Can you try running `./script/make-pretty`?

**Comment by Vyrastas** [comment]
Done, sorry I keep forgetting about that

**Comment by srickardti** [comment]
This looks good to me. Do you want to merge it and then I offer a PR to update the contents? I'm not sure if I can edit the branch the PR is based on.

**Comment by jwhui** [comment]
> This looks good to me. Do you want to merge it and then I offer a PR to update the contents? I'm not sure if I can edit the branch the PR is based on.

@srickardti , we'll merge this first and then you can submit a PR with your updates. Thanks!

**Review by jwhui — APPROVED** [review]

**Pull request merged**
