### PR TITLE
[docs] remove outdated build instructions from CLI docs

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Review by simonlingoogle — COMMENTED** [review]
Are they still valid at least for simulation?

**Comment by jwhui** [comment]
> Are they still valid at least for simulation?

At the very least, we should encourage CMake/Ninja.

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Review by Irving-cl — APPROVED** [review]
LGTM 👍

**Pull request merged**
