### PR TITLE
[tests] test updating SRP host address

### PR DESCRIPTION
**Pull request by wgtdkp**
Test if we can update the host address.

### CODE REVIEW

**Review by abtink — APPROVED** [review]
Thanks. LGTM. 👍

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Review by librasungirl — COMMENTED** [review]
For completeness, should we also verify that advertising proxy could respond the right/updated address when the host on the infrastructure link want to query and talk with the service provider?

**Comment by wgtdkp** [comment]
> For completeness, should we also verify that advertising proxy could respond the right/updated address when the host on the infrastructure link want to query and talk with the service provider?

@librasungirl  Thanks! Makes sense to me, will add the same case for Advertising Proxy soon.

**Review by librasungirl — APPROVED** [review]

**Review by jwhui — APPROVED** [review]

**Pull request merged**
