### PR TITLE
[crypto] remove unused references to get key attributes

### PR DESCRIPTION
**Pull request by hemanth-silabs**
We have some unused references to get key attribute feature. This PR aims to remove these.

### CODE REVIEW

**Comment by hemanth-silabs** [comment]
@abtink There were few unused references in the crypto and storage modules. I have removed these, can you review this PR?

**Review by abtink — APPROVED** [review]
LGTM. 👍

**Comment by hemanth-silabs** [comment]
@abtink @jwhui Do we need to increment the API version here? I have not changed any API signatures

**Comment by abtink** [comment]
> @abtink @jwhui Do we need to increment the API version here? I have not changed any API signatures

Yes, we need to change it. Any change (even if it is in the docs) of any of platform or public header requires an API version increment (the `api-check` script just checks for any diff in any of these files). It is safer to do so, since even a doc only change may explain a difference in some behavior (without any API signature change).

**Comment by hemanth-silabs** [comment]
@jwhui Can you review this as well?

**Comment by hemanth-silabs** [comment]
Thanks @abtink I pushed the update.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
