### PR TITLE
Tcat client fixes

### PR DESCRIPTION
**Pull request by canisLupus1313**
Minor fixes and improvements on TCAT client including:
-  fix in handling cert-path in can command
-  adding timeouts during BLE TLS connection establishement.

### CODE REVIEW

**Review by maciejbaczmanski — APPROVED** [review]
LGTM, there are missing new lines at the end of `ble_stream.py` and `base_commands.py`

**Comment by canisLupus1313** [comment]
@jwhui @abtink Can I cont on your review here?

**Review by abtink — APPROVED** [review]
👍

**Comment by jwhui** [comment]
@canisLupus1313 , would you like to have these commits squash-merged or merged separately? If so, can you add the PR# into the commit title?

For example:
```
[tcat] add timeout while connecting over BLE (#10597)
```

**Comment by canisLupus1313** [comment]
> @canisLupus1313 , would you like to have these commits squash-merged or merged separately? If so, can you add the PR# into the commit title?
> 
> For example:
> 
> ```
> [tcat] add timeout while connecting over BLE (#10597)
> ```

I have added the PR number to commit.

**Comment by canisLupus1313** [comment]
@jwhui Sorry I misunderstood you. I have updated the PR.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
