### PR TITLE
[clang-tidy] misc-unused-using-decls

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Review by abtink — APPROVED** [review]
LGTM. 👍

**Review by Irving-cl — APPROVED** [review]
LGTM

**Review by librasungirl — APPROVED** [review]

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Comment by simonlingoogle** [comment]
Not directly related by this PR, but I think the `script/make-pretty clang-tidy` is currently fixing `.h` headers in third_party/ directory (specifically mbedtls/cipher.h) by changing NULL to nullptr.

I investigated on this issue for a little while but couldn't find a suitable solution. Maybe we can fix this using the `-header-filter` argument or .clang-tidy configurations. However there seems no obvious solution to it. 

Thoughts? @jwhui

**Comment by jwhui** [comment]
> Not directly related by this PR, but I think the `script/make-pretty clang-tidy` is currently fixing `.h` headers in third_party/ directory (specifically mbedtls/cipher.h) by changing NULL to nullptr.
> 
> I investigated on this issue for a little while but couldn't find a suitable solution. Maybe we can fix this using the `-header-filter` argument or .clang-tidy configurations. However there seems no obvious solution to it.
> 
> Thoughts? @jwhui

@simonlingoogle , I noticed this as well. However, I'm not yet able to determine how to ignore files in `third_party/`. For the `check` option, I had to explicitly grep the output file and exclude paths including `third_party/`.

https://github.com/openthread/openthread/blob/fc159a706f0f1fbdffb526cad8e5847209dd6b14/script/make-pretty#L174

**Pull request merged**
