### PR TITLE
[gcov] use __gcov_dump() instead for clang 12

### PR DESCRIPTION
**Pull request by romacdon**
This is a follow on change to #7629

### CODE REVIEW

**Comment by bukepo** [comment]
can we add a check for clang 13? https://github.com/openthread/openthread/blob/main/.github/workflows/build.yml#L219

**Comment by romacdon** [comment]
> can we add a check for clang 13? https://github.com/openthread/openthread/blob/main/.github/workflows/build.yml#L219

@bukepo Yes, I can add this.  Should I also add versions 10, 11, and 12?  In addition should I add these versions to https://github.com/openthread/openthread/blob/main/.github/workflows/build.yml#L242 as well?

**Comment by romacdon** [comment]
> > can we add a check for clang 13? https://github.com/openthread/openthread/blob/main/.github/workflows/build.yml#L219
> 
> @bukepo Yes, I can add this. Should I also add versions 10, 11, and 12? In addition should I add these versions to https://github.com/openthread/openthread/blob/main/.github/workflows/build.yml#L242 as well?

@bukepo I went ahead and added versions "10", "11", "12", "13" to both locations.

**Comment by bukepo** [comment]
> 

from https://apt.llvm.org/, it seems we can add the following sources for clang 13 and 14:
```
deb http://apt.llvm.org/focal/ llvm-toolchain-focal main
deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main
# 13
deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main
deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main
# 14
deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main
deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main
```

**Comment by bukepo** [comment]
try the patch in: https://github.com/bukepo/openthread/commit/ef77737592438095ccaa0c8321d421e209e9ebd4

**Comment by bukepo** [comment]
> > try the patch in: [bukepo@ef77737](https://github.com/bukepo/openthread/commit/ef77737592438095ccaa0c8321d421e209e9ebd4)
> 
> @bukepo - I merged in your changes then made some additional changes to get clang and clang-m32 in sync. The tests are running now. Hopefully this is succesful.

Thanks, the toolchain is installed successfully. However, there are some build errors with clang-13. Could you please fix them?

**Comment by romacdon** [comment]
> > > try the patch in: [bukepo@ef77737](https://github.com/bukepo/openthread/commit/ef77737592438095ccaa0c8321d421e209e9ebd4)
> > 
> > 
> > @bukepo - I merged in your changes then made some additional changes to get clang and clang-m32 in sync. The tests are running now. Hopefully this is succesful.
> 
> Thanks, the toolchain is installed successfully. However, there are some build errors with clang-13. Could you please fix them?

Thanks once again @bukepo.  Just fixed the errors with clang-12 and clang-13.  Let's see what the test show now.

**Comment by bukepo** [comment]
> > > > try the patch in: [bukepo@ef77737](https://github.com/bukepo/openthread/commit/ef77737592438095ccaa0c8321d421e209e9ebd4)
> > > 
> > > 
> > > @bukepo - I merged in your changes then made some additional changes to get clang and clang-m32 in sync. The tests are running now. Hopefully this is succesful.
> > 
> > 
> > Thanks, the toolchain is installed successfully. However, there are some build errors with clang-13. Could you please fix them?
> 
> Thanks once again @bukepo. I just fixed the errors with clang-12 and clang-13. Let's see what the tests show now.
> 
> Update: I see failures already with my change for clang-12 errors. I will need to investigate further.

@romacdon Looks like the error only exists on macOS. Can we condition out macOS?

**Pull request closed without merging**
