### PR TITLE
[mbedtls] move mbedtls to 2.28.0 LTS version

### PR DESCRIPTION
**Pull request by jwhui**
As discussed in https://github.com/openthread/openthread/discussions/7527 .

### CODE REVIEW

**Comment by gabekassel** [comment]
I've tested this in two OTBR implementations on host side with EFR32 and Qorvo radios. Devices can attach, pass traffic, converge over TREL, etc. I've not tested an end device or joiner functionality yet.

**Comment by gabekassel** [comment]
I've tested this in two OTBR implementations on host side with EFR32 and Qorvo radios. Devices can attach, pass traffic, converge over TREL, etc. I've not tested an end device or joiner functionality yet.

**Review by gabekassel — APPROVED** [review]
feels shippable based on my testing so far, but would love others to do more bench testing.

**Review by LuDuda — APPROVED** [review]
Manually tested that commissioner & joiner works on nRF52840, also cross-checked with 2.25.

**Comment by hemanth-silabs** [comment]
Tested basic commissioning ping and UDP tests on EFR32MG12. LGTM 👍

**Review by hemanth-silabs — APPROVED** [review]

**Pull request merged**
