### PR TITLE
[efr32] fix assert triggered in otPlatRadioTransmit (#3768)

### PR DESCRIPTION
**Pull request by marvensilabs**
Fix for assert in otPlatRadioTransmit on efr32 platforms (#3768).

### CODE REVIEW

**Comment by marvensilabs** [comment]
Added fix for efr32mg21 NCP build issue with addition of  OPENTHREAD_CONFIG_NCP_UART_ENABLE.

**Comment by marvensilabs** [comment]
@jwhui 
Can we hold this pull request for a while.  We are updating the assert fix.

**Comment by marvensilabs** [comment]
Changed sTransmitError in otPlatRadioTransmit in efr32 mg12 and mg21 radio.c to set the transmit error to OT_ERROR_CHANNEL_ACCESS_FAILURE to avoid default assert in SubMac::HandleTransmitDone

**Comment by jwhui** [comment]
@marvensilabs, thanks for the update. I've marked this PR as work-in-progress. Let us know when you think this PR is ready to move forward again.

**Comment by marvensilabs** [comment]
@jwhui 

Changes we needed to make are in the latest commit and fixed an assert being triggered during testing.  We are happy for this to move forward.

**Comment by jwhui** [comment]
@marvensilabs, thanks for the update!

**Pull request merged**
