### PR TITLE
Add/remove CoAP resources as needed.

### LINKED ISSUE #575: Leader::Stop() doesn't remove 'a/sd' resource.
This is a minor issue. When a leader drops the role (when it changes partition) it doesn't remove the 'a/sd' resource.

### PR DESCRIPTION
**Pull request by jwhui**
Resolves #575.

### CODE REVIEW

**Comment by mszczodrak** [comment]
LGTM

**Comment by mszczodrak** [comment]
LGTM

**Comment by mszczodrak** [comment]
👍

**Comment by mszczodrak** [comment]
LGTM 👍

**Comment by wbober** [comment]
LGTM

**Pull request merged**
