### PR TITLE
[efr32] add CMake support

### PR DESCRIPTION
**Pull request by lmnotran**
This PR adds CMake support for the efr32 platforms and Silicon Labs gecko_sdk_suite. It also adds the option to build the efr32 sleepy-demo apps.

---
# Other changes
- **jlinkrtt**: remove NordicSemi specific options/definitions/includes from
default build
- Remove old include dirs that don't exist anymore from efr32 automake files

### CODE REVIEW

**Review by romacdon — APPROVED** [review]
LGTM

**Comment by jwhui** [comment]
@lmnotran , looks like the pretty-check is currently failing on the markdown check.

**Comment by lmnotran** [comment]
@jwhui Thanks! It should be fixed now

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
