### PR TITLE
[build] rename example platform POSIX to simulation

### PR DESCRIPTION
**Pull request by bukepo**
People are confused about the two POSIX platforms: example POSIX and
POSIX-app. This PR renames the example platform POSIX to
sim(simulation), and after this is merge, another PR will rename the
current POSIX-app to POSIX.

### CODE REVIEW

**Comment by simonlingoogle** [comment]
> People are confused about the two POSIX platforms: example POSIX and POSIX-app. 

Why is `src/posix/Makefile-posix`'s location so special? Why not `examples/Makefile-sim` and `examples/Makefile-posix`?

**Comment by bukepo** [comment]
All production-level code are supposed to be under src/. @simonlingoogle

**Comment by Vyrastas** [comment]
FYI after this goes in we'll have to update our Simulation Codelab and all references on openthread.io for a Posix build (which there are many).

**Comment by simonlingoogle** [comment]
> FYI after this goes in we'll have to update our Simulation Codelab and all references on openthread.io for a Posix build (which there are many).

After Docs are updated, it might be misleading for users who prefer to use [releases](https://github.com/openthread/openthread/releases).

**Comment by bukepo** [comment]
@Vyrastas Yes, we have to update openthread.io and codelab accordingly. However, as mentioned in description, this PR resolves confusions in longer term. Thoughts? @jwhui

**Comment by jwhui** [comment]
> @Vyrastas Yes, we have to update openthread.io and codelab accordingly. However, as mentioned in description, this PR resolves confusions in longer term. Thoughts? @jwhui

Should we stage the required doc changes so that we can update source and docs at nearly the same time?

/cc/ @Vyrastas

**Comment by Vyrastas** [comment]
If you can wait a day or two, I can do the documentation updates ahead of merging this.

**Comment by jwhui** [comment]
> If you can wait a day or two, I can do the documentation updates ahead of merging this.

Sounds good to me. Thanks, @Vyrastas !

**Comment by Vyrastas** [comment]
There is some example output on openthread.io that has this:

`wpantund[139]: NCP is running "OPENTHREAD/20170716-00967-g677d49b4; POSIX; Oct 18 2018 08:19:20"`

Is that version string going to change as part of this or will it still say "POSIX"?

**Comment by jwhui** [comment]
> There is some example output on openthread.io that has this:
> 
> `wpantund[139]: NCP is running "OPENTHREAD/20170716-00967-g677d49b4; POSIX; Oct 18 2018 08:19:20"`
> 
> Is that version string going to change as part of this or will it still say "POSIX"?
> 
> From here: https://github.com/openthread/wpantund/blob/master/src/wpantund/NCPInstanceBase.cpp#L264

@Vyrastas, good catch. @bukepo, we should also change the platform info string to something like "SIM" or "SIMULATION".

https://github.com/openthread/openthread/blob/cec297475f3af986022b701751622a0604db7cd7/examples/platforms/posix/openthread-core-posix-config.h#L48

**Comment by bukepo** [comment]
@Vyrastas @jwhui This PR uses `sim`, but I don't know whether we should use full `simulation`.  I'm fine with either way, but if you have any preference, I'm happy to change it.

**Comment by librasungirl** [comment]
no strong preference. `simulation` might be easier in keeping wording consistence in code/comment/document.

**Comment by Vyrastas** [comment]
Will the existing Docker images pick up this change too?

**Comment by jwhui** [comment]
> Will the existing Docker images pick up this change too?

Yes, I believe so.

**Pull request merged**
