### PR TITLE
[tcplp] remove unused type defines

### PR DESCRIPTION
**Pull request by bukepo**

### CODE REVIEW

**Comment by samkumar** [comment]
I agree that removing unused definitions from `types.h` could be beneficial. You seem to have left `caddr_t` and `c_caddr_t` in the code, but I would have removed them. Was that intentional?

I understand the reasoning behind removing `__int64_t` and `__uint64_t`, but I think we should leave them in for symmetry (it seems kind of odd to define `__int32_t` but not `__int64_t`). Additionally, since this code is derived from FreeBSD, I'd rather minimize the number of changes from the FreeBSD version (except for outright deletions), so I'd rather keep the original definition of `u_int64_t`, even if it means keeping `__uint64_t`. That said, these are minor points that won't affect functionality, and there are arguments on both sides, so I don't feel strongly about it.

I agree with the rest of your changes in this pull request.

**Comment by bukepo** [comment]
> I agree that removing unused definitions from `types.h` could be beneficial. You seem to have left `caddr_t` and `c_caddr_t` in the code, but I would have removed them. Was that intentional?
> 
> I understand the reasoning behind removing `__int64_t` and `__uint64_t`, but I think we should leave them in for symmetry (it seems kind of odd to define `__int32_t` but not `__int64_t`). Additionally, since this code is derived from FreeBSD, I'd rather minimize the number of changes from the FreeBSD version (except for outright deletions), so I'd rather keep the original definition of `u_int64_t`, even if it means keeping `__uint64_t`. That said, these are minor points that won't affect functionality, and there are arguments on both sides, so I don't feel strongly about it.
> 
> I agree with the rest of your changes in this pull request.

Hi @samkumar I remove these definitions so that the code can be built by toolchains already have those definitions.  Here's the failure: https://github.com/openthread/ot-br-posix/runs/4309864919?check_suite_focus=true
I found only 64bit types are causing conflicts, so I removed them only. Do you have any suggestions no resolving the failure?

**Comment by samkumar** [comment]
Thanks @bukepo for sharing those details. I didn't realize that the build was failing for platforms that already defined those types.

I did resolve one set of issues in Pull Request #7190, which involves the #include guards causing problems for the build in platforms that have similarly named files. `sys/types.h` was affected by this (since the #include guard conflicted with other files named `sys/types.h`). Can you check if the build issues show up with the code in that pull request?

I'll take a closer look at this issue in the next few days.

**Comment by jwhui** [comment]
TCP-related build failures on ot-br-posix are causing the build checks on the submodule updates to fail (e.g. https://github.com/openthread/ot-br-posix/pull/1123).

@samkumar , suggestions on how best to move forward?

**Comment by samkumar** [comment]
@jwhui Thanks for the heads up. I will take a look at those failures now.

**Comment by samkumar** [comment]
I took a look at the build failures and managed to reproduce the issue on my laptop. I managed to solve the build issue by removing the quad definitions (`u_quad_t`, `quad_t`, and `qaddr_t`) from `bsdtcp/types.h`.

This pull request (which seems to have been revised since I last looked at it) removes additional type definitions, which I entirely support. I checked that the latest version of the TCPlp code (in Pull Request #7190) still builds properly with these changes. I know I said above that I wanted to minimize the changes to FreeBSD code, but in this case I think that it is useful, because in this case, so much has been removed from `sys/types.h` already that it's probably not worth trying to minimize additional changes. I also like the simplicity of the latest version (defining only the unsigned integrals and nothing else).

I think that the appropriate path forward to resolve the build issues is to merge the current pull request. I will review it ASAP so that that can happen soon.

**Review by samkumar — APPROVED** [review]
Overall, this looks good and I appreciate the simplifications.

My only suggestion is to a comment about the type definitions that you deleted, or modify the existing comment I wrote at the top to mention them. The reason is that if we ever decide to update our code with upstream code that uses these types, it will be good to have this explained in a comment in order to restore the type definitions. That said, I don't feel too strongly about this and I am happy to merge this as is if you disagree with my suggestion.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
