### PR TITLE
Enable Windows WPP Logging Support

### PR DESCRIPTION
**Pull request by nibanks**
Windows WPP logging allows for each logging to a file. One thing to note, WPP doesn't work inside other defines or in header files. So there were a few places I had to modify the logging line.

### CODE REVIEW

**Comment by nibanks** [comment]
I'm not sure why Cert_5_2_02_LeaderReject1Hop.py failed on Travis-CI, but it succeeded [on my branch](https://travis-ci.org/nibanks/openthread/builds/162217951).

**Comment by darconeous** [comment]
Is there any way to include these files on the command line for compiling the individual files? I'm inclined not to want to take this because of the unique boilerplate required for so many files.

**Comment by nibanks** [comment]
WPP (see [docs](https://msdn.microsoft.com/en-us/library/windows/hardware/dn914598(v=vs.85).aspx)) requires you to include the .*tmh directly in the file. I tried to find if there is anyway to get just the file name (no path or ext) via the preprocessor but couldn't find any way. The best I could do would be change

```
#ifdef WINDOWS_LOGGING
#include "mac.tmh"
#endif
```

to something like

`PLATFORM_PREPROCESS("mac")`

and that would be defined to include the necessary file on Windows and do nothing everywhere else. What do you think?

**Comment by darconeous** [comment]
Wow, does that actually work? The Visual Studio preprocessor must be a lot more expressive than a normal preprocessor, since I'm not quite sure how you are able to do that with just standard C preprocessor macros. :)

It's better. Still weird, but it is better. I think I could live with something like that if @jwhui and others could.

**Comment by nibanks** [comment]
So how about this solution, in each source file that needs WPP logging, at the top of the file I define the following:

`#define WPP_NAME "mac.tmh"`

Then in `common/logging.hpp` I define the following:

```
#ifdef WINDOWS_LOGGING
#ifdef WINDOWS_KERNEL
#include <wdm.h>
#endif
#include <platform/logging-windows.h>
#ifdef WPP_NAME
#include WPP_NAME
#endif
#endif
```

It seems to work and is fairly simple.

**Comment by darconeous** [comment]
Did your idea solution not work?

**Comment by nibanks** [comment]
No, my original plan didn't work. This is the only thing I could get to work.

**Pull request merged**
