### PR TITLE
Added iar project files for cc2538 example.

### PR DESCRIPTION
**Pull request by turon**

### CODE REVIEW

**Comment by jwhui** [comment]
This PR has gone stale. I'm going to close it for now. We can reopen this in the future if needed.

**Comment by mstamer** [comment]
@jwhui @turon 
Any chance to bring this back from the dead?  It would be a great example for others(myself) tied to IAR and its IDE environment to start from (still have to migrate to different chipset)
Thanks,
-mike

**Comment by jwhui** [comment]
@mstamer, to officially include them in the OpenThread project, we need a person/organization to provide long-term commitment to:

- Continuously update and maintain OpenThread IAR project files as the OpenThread code evolves.
- Support users of OpenThread with IAR.
- Add continuous integration support for OpenThread with IAR.

Currently, we have GNU Tools and Windows Visual Studio which satisfy the above criteria.  If we can find the same for IAR, then we can consider inclusion into the OpenThread project.

**Comment by TomGardner** [comment]
@jwhui  @turon 
I'm trying to get IAR Workbench for ARM on Windows working on Silicon Labs EM35x / EFR32 environment using these files as a start.
Is there a openthread-config-generic.h file somewhere for IAR?
Thanks,
-tomg

**Comment by jwhui** [comment]
@TomGardner, here are a couple files that should help:
1. [openthread-config-generic.h.in](https://github.com/openthread/openthread/files/1415243/openthread-config-generic.h.in.txt) - template that is generated as part of `./bootstrap`
2. [openthread-config-generic.h.txt](https://github.com/openthread/openthread/files/1415246/openthread-config-generic.h.txt) - generated as part of `make -f examples/Makefile-cc2538`

Hope that helps.

**Comment by TomGardner** [comment]
Great. Thanks.
I ran 'make -f examples/Makefile-efr32' to get the one I needed.

**Pull request closed without merging**
