### PR TITLE
Add missing definitions for stdint.h and stdbool.h for Windows Kernel mode

### PR DESCRIPTION
**Pull request by nibanks**
Move stdint.h and stdbool.h references into new openthread-std-types.h file that can be used to easily abstract these usages in Windows kernel mode and replace their usages with the equivalent.

### CODE REVIEW

**Comment by darconeous** [comment]
These changes (changing all references to `<stdint.h>` to `<openthread-std-types.h>`) are not acceptable.

An acceptable alternative would be to create a file named `stdint.h` in the folder `src/replacements/stdint/`. This folder would be included in the system path on systems without `stdint.h`. I assume the same would apply for `stdbool.h`.

**Comment by darconeous** [comment]
Pinging @jwhui and @abtink to comment on my proposed alternative and the path `src/replacements/stdint/` and `src/replacements/stdbool/`.

Now that I think more about it, perhaps `src/missing/stdint/` and `src/missing/stdbool/` would be better. Thoughts?

**Comment by darconeous** [comment]
@nibanks: Seems like `src/missing/stdint/` and `src/missing/stdbool/` are what we are going with.

**Comment by abtink** [comment]
I agree with the not changing/renaming the "stdint.h" file. I also like the`src/missing/stdint/` as the location.

**Comment by nibanks** [comment]
Ok. I will make the updates. Thanks.

**Comment by darconeous** [comment]
The use those files is not acceptable: They copyrighted and privately-licensed, not open-source.

However, both files are pretty braindead. You should be able to write fresh ones from scratch (like you presumably did for `openthread-std-types.h`) without too much trouble.

**Comment by darconeous** [comment]
👍  LGTM

**Comment by jwhui** [comment]
LGTM 👍

**Pull request merged**
