### PR TITLE
Include platform details in version information

### LINKED ISSUE #331: Include platform details in version information
OpenThread will be built on various platforms, it would be better to include platform details in the version information, such as:
_OPENTHREAD/g20b5de8, POSIX/xxx; Aug  4 2016 10:48:24
OPENTHREAD/g20b5de8, CC2538/xxx; Aug  4 2016 10:48:24_

### PR DESCRIPTION
**Pull request by chshu**
- add --with-platform-info configuration option to specify platform information
  - add otGetVersionString() interface to get OpenThread version

Resolves #331.

### CODE REVIEW

**Comment by mszczodrak** [comment]
LGTM :+1:

**Comment by jwhui** [comment]
@darconeous, is updating the version information in this way OK for `wpantund`?

**Comment by darconeous** [comment]
having a look

**Comment by darconeous** [comment]
I don't mind capability, but it needs to be implemented in a way that preserves the string in the memory of the image. We do firmware upgrade checks by fetching the firmware version string from the NCP and then searching for that exact string somewhere in the firmware image that we are considering installing. If the string is found, we assume no firmware upgrade is necessary. If the string is not found, we assume that we have a different firmware image and go ahead and install it.

One way to fix this is to not use `printf`-style construction, but use the preprocessor macros directly. We can do that by moving the construction of that version check string into OpenThread and making it the `otGetPlatformVersion()` command:

```
const char *otGetPlatformVersion(void)
{
    static const char sPlatformVersion[] = PACKAGE_NAME "/" PACKAGE_VERSION "; " OPENTHREAD_EXAMPLES "; " __DATE__ " " __TIME__;

    return sPlatformVersion;
}
```

...and then we can have both the CLI and NCP directly return that string.

On an unrelated note, we should really rename `OPENTHREAD_EXAMPLES`. It is very confusing how it is being used in this context.

**Comment by chshu** [comment]
@darconeous Thanks for the suggestion, but this method does not work for the case if we build OpenThread on some other platforms which are built out of OpenThread repository, It doesn't know the OpenThread version information in the independent platform layer (Marble is an example).

My design is to keep the OpenThread library version as it is, and attach another platform version reading from **otGetPlatformVersion**() interface, no matter how the platform library is built, it just need to provide a **otGetPlatformVersion**() interface for retrieving its platform version.

About the version string comparison in firmware update, is it possible to only search the time field in the firmware image? For example: if the current NCP version is "OPENTHREAD/gb93cdcd; cc2538; Aug  9 2016 15:37:57", then we could search "Aug  9 2016 15:37:57" in the the firmware image to determine whether install it or not?

**Comment by darconeous** [comment]
Ok, I see where you are coming from.

I'd rather not make any assumptions about the version string, other than mandating that it be represented in the firmware image as a continuous string. Trying to parse it to extract the date is likely to be error-prone.

Now that I understand what you are trying to accomplish, here is my new proposal:

Let's rename the function from `otGetPlatformVersion()` to `otGetVersionString()` and move it out of the platform and into OpenThread. Then let's modify the function to include the ability to add things to the version string at build time:

```
const char *otGetVersionString(void)
{
    static const char sPlatformVersion[] =
        PACKAGE_NAME "/" PACKAGE_VERSION "; "
#ifdef OT_EXTRA_VERSION_INFO
        OT_EXTRA_VERSION_INFO "; "
#endif
        __DATE__ " " __TIME__;

    return sPlatformVersion;
}
```

We then allow `OT_EXTRA_VERSION_INFO` to be set by the user via a `configure` command-line argument. This would allow builds with external platforms to specify any additional build information directly into the version string in a way that produces a single coherent string in firmware.

If `OT_EXTRA_VERSION_INFO` is not specified on the command line, then it is either left undefined or set to `OPENTHREAD_EXAMPLES` if that is set.

For example, with the above mechanism implemented, the marble build system would call `configure` with something like this:

```
./configure --with-extra-version-info="Marble/`git describe --always`"
```

Thoughts?

**Comment by chshu** [comment]
@darconeous I have followed your proposal and updated the implementation of this PR, so then we can specify the platform information with configuration option when building with either internal or external platform. And it will not affect the firmware update logic. Please have a review, thanks.

**Comment by darconeous** [comment]
Looks fantastic!

👍

**Comment by jwhui** [comment]
LGTM 👍

**Pull request merged**
