### PR TITLE
otPlatform: New non-volatile settings API

### PR DESCRIPTION
**Pull request by darconeous**
This is the new API for the storage and retrieval of non-volatile
settings. Platforms would implement this API in order to allow various
types of information to be preserved across resets or power loss.

### CODE REVIEW

**Comment by darconeous** [comment]
This is a new API, so some discussion is warranted.

This API is different from the original one I proposed in email: I have removed the ability to store more than one value per key. I found @pvanhorn's arguments compelling, but if that capability was going to be useful then I can put it back in.

**Comment by mszczodrak** [comment]
LGTM :+1:

**Comment by jwhui** [comment]
From what I've gathered so far, the per-child state is 13 bytes.  To support 64 children, that would mean the child list is more than 800 bytes.  Is updating the child list setting every time a child attaches/detaches acceptable for platforms implementing this API?

**Comment by darconeous** [comment]
@jwhui: When you put it like that, it sounds like a really good reason for us to go with the extended API with the index support. :)

I'll make those changes.

**Comment by darconeous** [comment]
Updated.

**Comment by darconeous** [comment]
In any case, we should be careful how often we write out things like child lists. That could be hard on the flash.

**Pull request merged**
