### PR TITLE
[net] fix typo multicast in comments

### PR DESCRIPTION
**Pull request by gm-jiang**
fix typo multicast in comments

### CODE REVIEW

**Review by wgtdkp — APPROVED** [review]

**Comment by jwhui** [comment]
@gm-jiang , thank you for submitting this PR!

Please resolve the CLA issue so that we can move this PR forward.

**Comment by esp-jiangguangming** [comment]
> @gm-jiang , thank you for submitting this PR!
> 
> Please resolve the CLA issue so that we can move this PR forward.

@jwhui okay, will do that.

**Comment by jwhui** [comment]
@gm-jiang , any update on resolving the CLA issue?

**Comment by esp-jiangguangming** [comment]
@jwhui PTAL https://github.com/openthread/openthread/pull/8755

**Comment by jwhui** [comment]
Superseded by #8755

**Pull request closed without merging**
