### PR TITLE
update child's keep alive

### PR DESCRIPTION
**Pull request by librasungirl**
- use defined MLE_END_DEVICE_TIMEOUT(240s) as child's timeout period;
 - all 4 keep-alive attempts completed in MLE_END_DEVICE_TIMEOUT;

as required in Chapter 4.7.5.

@jwhui , please have a review.

### CODE REVIEW

**Comment by jwhui** [comment]
Thanks for addressing this.  I think this is fine for now, but I think we could be more efficient about sending the Child Update Request/Data Poll messages.  In particular, if there is no message loss, we should only send one message per MLE_END_DEVICE_TIMEOUT period.  That means we could define a relatively small retry period and only start trying to send a Child Update Request message at MLE_END_DEVICE_TIMEOUT - 4 * X, where X is the retry period.

**Comment by jwhui** [comment]
LGTM 👍

**Comment by librasungirl** [comment]
Hi Jonathan,

Agree and thanks for the suggestion.

Will improve the code later.


Thanks & BRs
Rongli Sun

**Comment by librasungirl** [comment]
Sorry, planned to ask you about hold time in separate email, but didn't
remove the attachment in last email. So just ask here:

In thread 1.0, hold time is defined as 90s.  Thread 1.1 says 'minimum
payload size and hold times are detailed in the Thread Conformance
specification'. However the ConformanceDocument I got from Tom doesn't
include any definition for hold time.  Confusingly, in Chapter 4.7.4 of
below attached document (from SPEC-419
<https://threadgroup.atlassian.net/browse/SPEC-419> ), one paragraph about
hold time is as below:

Parent devices are responsible for buffering messages for rx-off-when-idle
children. When buffering a message for a sleepy child, the parent SHALL
hold the message until it is delivered, or the child timeout occurs. This
hold time applies to both unicast and multicast messages.

Guess the above paragraph should be the truth. But it isn't included in
‘Thread1.1RC2Preview4Clean_1476_1.pdf’, nor in ConformanceDocument. Not
sure why.

Do you have any information about hold time?

Thanks&BR

Rongli Sun

**Comment by jwhui** [comment]
@librasungirl, the Hold Time as a separate parameter no longer exists.  Section 2.2, Item 3 of the Conformance document specifies the behavior of buffering messages for SEDs.

**Pull request merged**
