### PR TITLE
Reduce MTU to 1280 bytes

### LINKED ISSUE #842: MTU should be 1280 bytes
@nibanks brought to my attention that currently the MTU in OpenThread is being set to 1500 bytes. 

This value should be changed to 1280 bytes. Smaller packets means better performance. Using the minimum MTU ensures that we keep the amount of layer-2 fragmentation to a minimum. 

A busy TCP stream over a Thread network will perform worse with a 1500 MTU than a 1280 MTU.

### PR DESCRIPTION
**Pull request by nibanks**
Fixes #842.

### CODE REVIEW

**Comment by nibanks** [comment]
So it looks like the `Cert_5_1_07_MaxChildCount` test fails because it is sending a 1280 Echo Request. Should I just reduce that to something like 1000? Or do we want to modify the logic in `Ip6::HandleDatagram`? I think the test fails because it starts with a 1280 byte packet, but adds additional headers for routing.

**Comment by nibanks** [comment]
I reduced the test's ping to `1200` bytes and it fixed the problem. I think this is a good short term solution. Long term, we need to figure out how to handle incoming packets that are within our MTU requirement, but routing headers push them over.

**Comment by jwhui** [comment]
Thanks for looking into this.  Can you try with 1232 bytes?  That's what the official Thread Certification Harness uses.

**Comment by nibanks** [comment]
Checked in. We'll see if the tests succeed, but it looks like they should.

**Comment by nibanks** [comment]
Looks like it worked!

**Pull request merged**
