### PR TITLE
[joiner] fix code coverage typo

### PR DESCRIPTION
**Pull request by romacdon**
Fix code coverage typo

### CODE REVIEW

**Comment by romacdon** [comment]
@googlebot I signed it!

**Comment by romacdon** [comment]
@googlebot I signed it!

**Comment by romacdon** [comment]
@jwhui any idea why the googlebot thinks I haven't signed the CLA.  When I go to https://cla.developers.google.com/ it shows that I am included in the Silabs corporate CLA.

**Comment by jwhui** [comment]
> @jwhui any idea why the googlebot thinks I haven't signed the CLA. When I go to https://cla.developers.google.com/ it shows that I am included in the Silabs corporate CLA.

Not sure. Can you double check that the email address in your commit is included in the Google Group associated with your Corporate CLA?

**Comment by romacdon** [comment]
Already did that and it is.

**Comment by romacdon** [comment]
@googlebot I signed it!

**Comment by jwhui** [comment]
> Already did that and it is.

@romacdon, it appears the email address you used in this commit (Robert.MacDonald@) is different from what's included in the Google Group associated with your Corporate CLA (romacdon@). These two need to match for the check to pass. Can you check again?

**Comment by romacdon** [comment]
@googlebot I signed it!

**Comment by romacdon** [comment]
@jwhui you were correct. Thanks for checking. I fixed this and now the CLA check is passing.  Thanks.

**Comment by jwhui** [comment]
> @jwhui you were correct. Thanks for checking. I fixed this and now the CLA check is passing. Thanks.

Glad that it is working now!

**Pull request merged**
