### PR TITLE
[toranj] adding test-case for multi-hop traffic exchange

### PR DESCRIPTION
**Pull request by abtink**
This commit adds a new `toranj` test script to test IPv6 traffic  exchange over multiple hops in a network with chain topology:

```    
           r1 ----- r2 ---- r3 ----- r4
           /\       |       |        /\
          /  \      |       |       /  \
        fed1 sed1  sed2    sed3   sed4 fed4
```
  
Traffic flow:
- From first router to last router
- From SED child of last router to SED child of first router
- From FED child of first router to FED child of last router
    
 The test covers the following:
- Verifies Address Query process over multi-hop to routers and FEDs.
- Verifies Mesh Header frame forwarding over multiple routers.
- Verifies forwarding of large IPv6 messages (1000 bytes) requiring lowpan fragmentation.

### CODE REVIEW

**Comment by jwhui** [comment]
This is great.  What about also validating multihop traffic between FTD and MTD children across the same topology?

**Comment by abtink** [comment]
In the current test, every router has a SED child attached to it (need it to make sure routers are promoted quickly)
So this is the topology: 
```
r1 --- r2 --- r3 --- r4 
|      |      |      |
c1     c2     c3     c4
```
- The first part of the test we send from first router (r1) in the chain to the last router in the chain (rN).
- The second part we send from the child of last router (cN) to the child of first router (c1)

If you have ideas for more test let me know. It's easy to add it to the test.

**Comment by Nopik** [comment]
Speaking here about how to interpret Thread specification: assuming that link quality is good between all devices (each link cost = 1), what should be routing cost of r1 -> r4 route and what should be the cost of c4-c1 route?

Does it count only router-router cost? I.e. both costs should be calculated as 3?

**Comment by jwhui** [comment]
@Nopik, when routing a packet, the link cost between a given child and its parent are not factored in to the path/route cost.  To answer your question more directly, the answer is 3 for both.

The one minor exception is Router-Eligible End Devices (REEDs), which do compute their route cost to the leader and communicate that devices that are looking for a parent to attach to.

**Comment by jwhui** [comment]
@abtink, I think it may be useful to have a test that includes communication with Full End Devices (FEDs).  This will test the FED's ability to respond directly to Address Query in addition to sending/receiving IPv6 messages even while it does not participate as a Router.

**Comment by abtink** [comment]
@jwhui , sounds great... Added it in the new pushed commit.

**Pull request merged**
