### PR TITLE
Implement settings API, add flash API and implement posix and CC2538 flash driver

### LINKED ISSUE #325: CC2538 flash driver that supports non-volatile setting API
This issue mainly includes the following functions
- Flash Driver API (#485) 
- CC2538 Flash Driver
- Posix Flash Driver simulator (#605)
- OT Settings implementation

All the functions are implemented in PR #428 .
I closed it and would submit 4 separate PRs for each function of this issue.
It may be easier for code review.

### PR DESCRIPTION
**Pull request by luwannest**
Resolves #325 

- implement setting API
- add flash API interface
- implement posix flash driver that simulates 1 MB flash
- implement CC2538 flash driver

We can enable the settings test function and using posix implement for test purpose.

There are 2 ways to check the test result.
- the return value of the test function. No error code returns indicates success.
- check the file that simulates 1MB flash. The file is named as OT_Flash in the same folder that runs ot-cli.

We can also build CC2538 image for testing on CC2538 board.

object file size while building CC2538 image:
arm-none-eabi-size libopenthread_a-settings.o 
   text	       data	        bss	        dec	           hex	   filename
   3131	          4	        159	        3294	    cde	   libopenthread_a-settings.o

### CODE REVIEW

**Comment by luwannest** [comment]
@darconeous , could you have a review of this commit?
The main changes are to meet the following requirement
- easily port to different hardware platform that change the flash driver
- users can choose to use or not use settings management

**Comment by luwannest** [comment]
Thanks for the comments!
I will remove the ram data structure for management then searches flash directly when needed, and allocate the ram buffer for reordering when there is no space.
Just trying to improve the speed while searching and insert via add additional data structures.

@darconeous , I would prefer to remove key, but only use index for identifying. The key is no use for improving searching speed till my understanding. We always need to search the flash. Do you have any comments?

**Comment by jwhui** [comment]
@luwannest, the `key` identifies a particular setting and the `index` identifies a particular instance of that setting.  One example is a parent saving child state.  The child setting would have an assigned `key` and a given child would have an assigned `index`.

**Comment by luwannest** [comment]
Thanks @jwhui for the comments! Yes, it it better to use key + index that is easier to manage the settings belonging to the same group, and easier to guarantee the uniqueness.
Will submit a patch for reducing object file size.

**Comment by luwannest** [comment]
@darconeous ,@jwhui, could you help to take a look at the code for the settings, while you have time? Thanks!

**Comment by luwannest** [comment]
@darconeous , could you take a look at the code while you have time? Thanks!
I think that it makes a lot changes comparing with previous one.
If needed, I can divide them into small ones. That may be easier for review.

**Comment by luwannest** [comment]
Closing this PR. Will submit multiple smaller PRs for easier code review.

**Pull request closed without merging**
