### PR TITLE
Add Ncp counters: Num of tx/rx IP msgs, dropped IP msgs, spinel frames

### PR DESCRIPTION
**Pull request by abtink**
This PR adds support for some new counters (at NCP layer) such as number of received/transmitted IP msgs (secure vs. insecure), number of dropped rx/tx IP messages, and number of received/transmitted spinel frames..

### CODE REVIEW

**Comment by mszczodrak** [comment]
LGTM :+1:

**Comment by arjunasiva** [comment]
LGTM

**Comment by abtink** [comment]
ping @googlebot

**Comment by darconeous** [comment]
👍

**Comment by jwhui** [comment]
LGTM 👍

**Pull request merged**
