### PR TITLE
[codecov] cover swapping flash block of settings

### PR DESCRIPTION
**Pull request by bukepo**
This PR adds a self test to cover swapping block functionality. Since
find will include the `.o` file generated by the unittest program, how
the platform library find objects of the utils library is also updated.

### CODE REVIEW

**Comment by bukepo** [comment]
@jwhui any comments?

**Comment by bukepo** [comment]
Ping~

**Comment by jwhui** [comment]
@bukepo, I would like to move the `settings_flash.c` implementation into core. A build config can choose whether the OpenThread library calls `otPlatSettings*` APIs or something like `otPlatFlash*` APIs. Are you OK with waiting to merge this PR until after this move is complete?

**Comment by bukepo** [comment]
Yes, thanks for the information.

**Comment by bukepo** [comment]
I don't think the new implementation needs this change anymore. I will close this for now.

**Pull request closed without merging**
