### PR TITLE
[notifier] define 'kEventStrings[]' as const pointer

### PR DESCRIPTION
**Pull request by abtink**

### CODE REVIEW

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1: 

I tried the same change and compared the size, but didn't see any chance in code or memory size. Why does it has no impact on memory size?

**Review by Irving-cl — APPROVED** [review]
LGTM

**Comment by abtink** [comment]
> I tried the same change and compared the size, but didn't see any chance in code or memory size. Why does it has no impact on memory size?

@simonlingoogle , my guess is that complier may be already treating the array as a `const`.

**Comment by simonlingoogle** [comment]
> > I tried the same change and compared the size, but didn't see any chance in code or memory size. Why does it has no impact on memory size?
> 
> @simonlingoogle , my guess is that complier may be already treating the array as a `const`.

But I **did** see memory increase for `sThreadErrorStrings` if `*const` is not used. I think it's safer to always use `*const`.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
