### PR TITLE
[logging] fix format strings

### PR DESCRIPTION
**Pull request by andrei-menzopol**
This PR fixes the format string in logging functions. 

When openthread is included in other projects that use the `-Werror` option in their builds, such as Matter, these format string errors appear. In this case, it can be seen in [radio.h](https://github.com/openthread/openthread/blob/main/include/openthread/platform/radio.h#L360) that the structure members are `uint32_t` but printed with `%u`.

The size of types depends on the target, there needs to be a casing.

`
../../third_party/connectedhomeip/third_party/openthread/repo/src/lib/spinel/radio_spinel_impl.hpp:3035:43: error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 3035 |         otLogDebgPlat(" txGrantImmediate:%u", metrics.mNumTxGrantImmediate);
`

### CODE REVIEW

**Review by abtink — APPROVED** [review]
LGTM. Thanks. 👍

**Comment by andrei-menzopol** [comment]
Thank you

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Comment by jwhui** [comment]
@andrei-menzopol  , would you like to squash these commits or keep them separate? If you want to keep them separate, please include the PR # in the commit header. For example:

- `[spinel] fix format string in logging (#8446)`
- `[cli] fix format string in logging (#8446)`

**Comment by andrei-menzopol** [comment]
Thank you. I have squashed them.

**Comment by andrei-menzopol** [comment]
There are a few failed tests that need a rerun, I believe.

**Pull request merged**
