### PR TITLE
[efr32] fix build errors due to recent change of otUdp APIs

### PR DESCRIPTION
**Pull request by romacdon**
The PR which resulted in the compilation issues is: https://github.com/openthread/openthread/pull/5231

### CODE REVIEW

**Comment by romacdon** [comment]
@jwhui one of the checks failed and I'm sure it was test environment issue and not anything to do with this change.  Is there a way for me to kick off that test again or does that have to be done by you or someone with more privs than me?

**Comment by jwhui** [comment]
> @jwhui one of the checks failed and I'm sure it was a test environment issue and not anything to do with this PR. Is there a way for me to kick off that test again or does that have to be done by you or someone with more privs than me?

@romacdon , on the GitHub Actions page, do you see a "Re-run jobs" pull down in the upper right?
https://github.com/openthread/openthread/pull/5243/checks?check_run_id=873335271

**Comment by romacdon** [comment]
> > @jwhui one of the checks failed and I'm sure it was a test environment issue and not anything to do with this PR. Is there a way for me to kick off that test again or does that have to be done by you or someone with more privs than me?
> 
> @romacdon , on the GitHub Actions page, do you see a "Re-run jobs" pull down in the upper right?
> https://github.com/openthread/openthread/pull/5243/checks?check_run_id=873335271

@jwhui I do not see that option.

**Comment by jwhui** [comment]
@romacdon , it appears that permissions for re-running a workflow is based on permissions on the repo itself (only those with write or admin access). There is an outstanding [feature request](https://github.community/t/feature-request-re-run-checks-for-pr-authors/17907) to allow PR authors to re-run workflows, but I have not seen any update on that.

For now, I have triggered a re-run of the job.

**Pull request merged**
