### PR TITLE
[mle] set ChannelPage value in MLE Announce messages

### LINKED ISSUE #7282: rcp MLE Announce format error.
There are two format error in the Announce message.
1 The Fragmentation Header in 6LoWPAN layer is not need.
2 The Channel Page in MLE layer is error.

image

### PR DESCRIPTION
**Pull request by jwhui**
Fixes #7282

### CODE REVIEW

**Review by abtink — COMMENTED** [review]
👍

**Review by abtink — APPROVED** [review]

**Review by simonlingoogle — COMMENTED** [review]
What are the possible consequences of this bug?
@jwhui

**Comment by jwhui** [comment]
> What are the possible consequences of this bug? @jwhui

@simonlingoogle , given that existing implementations do not currently process the ChannelPage value, I don't think there are any issues today. However, future implementations may process the ChannelTlv value and reject invalid values.

**Comment by simonlingoogle** [comment]
> > What are the possible consequences of this bug? @jwhui
> 
> @simonlingoogle , given that existing implementations do not currently process the ChannelPage value, I don't think there are any issues today. However, future implementations may process the ChannelTlv value and reject invalid values.

Thanks for clarification.

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Pull request merged**
