### PR TITLE
[config] enable SRP/DNS client on Thread 1.3 or higher as default config

### PR DESCRIPTION
**Pull request by abtink**
This commit changes the default config headers to enable SRP and DNS
clients on Thread version 1.3 or higher by default. It also adds a
guard check in the config headers which use the thread version config
`OPENTHREAD_CONFIG_THREAD_VERSION` to ensure that it is defined.

### CODE REVIEW

**Comment by librasungirl** [comment]
DNS/SRP client might not be necessary for 1.3 BR?

**Comment by abtink** [comment]
> DNS/SRP client might not be necessary for 1.3 BR?

The idea behind this is to help make default configs be the ones often used (to make it easier for product/platform integrators).

It is true that BR may not be need DNS/SRP but I guess including it should be relatively harmless (it will be compiled but may not be used).
Also possible that a non-BR device wants to use its own SRP/DNS implementation (and not use OT implementation).

I think in such cases, the product integrator can choose to explicitly disable the feature (override the default).

Thoughts?

**Comment by librasungirl** [comment]
No strong preference. But for product/platform integrators, I think they should know the features and explicitly specify the features they want to enable, other than depend on the default configuration.

**Comment by abtink** [comment]
I am closing this PR. We can assume that users (project integrators) will explicitly select the set of features to enable.

**Pull request closed without merging**
