### PR TITLE
Enable IPv6 datagram filter by default from `NcpBase` constructor

### PR DESCRIPTION
**Pull request by abtink**

### CODE REVIEW

**Comment by abtink** [comment]
It reduces the traffic being sent to the host. The host should not anyways handle/process any of the MLE/Thread control traffic (which are already processed by OpenThread stack). It is a feature mainly used for debugging so makes sense to have the default setting as off and enable only if debugging is required.

**Comment by nibanks** [comment]
Enabling filtering prevents the RLOC address from being used (as all messages received for it are filtered), which is what a Border Agent must use.

**Comment by abtink** [comment]
Ok I see. 
I think we should consider adding different kind of filters (e.g. to block processed MLE but pass certain other messages).

**Comment by abtink** [comment]
We have a spinel property `THREAD_RLOC16_DEBUG_PASSTHRU` to enable RLOC16 traffic (which basically disables the filter).  And the documentation in [spinel-doc](https://github.com/openthread/openthread/blob/master/doc/draft-spinel-protocol.txt#L2413) mentions default should be `false` (meaning rloc 16 pass-thru is disabled or filter is up)...

My suggestion is to follow this and enable the filter by default and use the property  to change the behavior when it's needed.

**Comment by nibanks** [comment]
That's why I asked you to update the Windows driver to set the property along with this change, as long as you still are going to make this change. You would have to call something like this in `otLwfTunInitialize`:

```
    status =
        otLwfCmdSetProp(
            pFilter,
            SPINEL_PROP_THREAD_RLOC16_DEBUG_PASSTHRU,
            SPINEL_DATATYPE_BOOL_S,
            TRUE
        );
```

**Comment by abtink** [comment]
@nibanks, can you please help add this either on top of this branch/PR (I added your as collaborator on my fork) or in a different PR (up to you)..

You are definitely the window driver expert and main contributor to it...and I don't know much about it... I don't feel comfortable adding code under windows driver where I cannot locally compile and verify.. 
Thanks man...

**Comment by nibanks** [comment]
@googlebot I am OK with my changes in this PR

**Comment by abtink** [comment]
Thanks @nibanks ...

**Pull request merged**
