### PR TITLE
ncp: New API `otNcpStreamWrite()`

### PR DESCRIPTION
**Pull request by darconeous**
This API will initially be used for writing debug logs messages to
the host, but may in the future be expanded for other purposes.

This change also fixes a misspelling of "Property" in various
internal methods.

### CODE REVIEW

**Comment by darconeous** [comment]
Wups, don't merge, accidentally defined this new function in the `Thread` namespace. Will fix.

**Comment by darconeous** [comment]
Ok, I think this is all set.

**Comment by jwhui** [comment]
LGTM 👍

**Comment by abtink** [comment]
LGTM :+1:

**Pull request merged**
