### PR TITLE
[trel] TREL DNS-SD small updates and checks

### PR DESCRIPTION
**Pull request by simonlingoogle**
Based on #7125 

This commit (2nd commit) adds small updates and checks to TREL DNS-SD:
- Added platform API `trelDnssdInitialize` to initialize TREL DNS-SD module.
- Added a small check to verify TREL is working
- Fixed `Border Router` TREL test to really use TREL (was not actually working as intended)

Depends-On: openthread/ot-br-posix#1109

### CODE REVIEW

**Comment by abtink** [comment]
The second commit LGTM. Thanks.

**Comment by simonlingoogle** [comment]
@abtink 

I have add a TREL to verify that TREL is working. Please take another look at the two commits.

**Review by abtink — APPROVED** [review]
Thanks. LGTM. 👍

**Comment by abtink** [comment]
Closing this PR as its commits are already merged into `main` as part of 
- https://github.com/openthread/openthread/pull/7371

**Pull request closed without merging**
