### PR TITLE
[efr32] move to openthread/ot-efr32

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Review by lmnotran — APPROVED** [review]
LGTM.

One tangentially related question: Do you know who should be responsible for updating the markdown files in [`doc/site/en/guides/porting`](https://github.com/openthread/openthread/tree/main/doc/site/en/guides/porting)?

**Comment by jwhui** [comment]
> One tangentially related question: Do you know who should be responsible for updating the markdown files in [`doc/site/en/guides/porting`](https://github.com/openthread/openthread/tree/main/doc/site/en/guides/porting)?

As FYI, we are transitioning the openthread.io doc sources to https://github.com/openthread/ot-docs/

Would Silicon Labs be willing to help make the update to the porting guide?

**Review by romacdon — APPROVED** [review]
LGTM

**Comment by romacdon** [comment]
> 
> Would Silicon Labs be willing to help make the update to the porting guide?

Yes.

**Comment by jwhui** [comment]
> > Would Silicon Labs be willing to help make the update to the porting guide?
> 
> Yes.

@romacdon , thanks! Looking forward to the contribution.

**Comment by lmnotran** [comment]
@jwhui Do you want me to just open a separate PR to the `ot-docs` repo so that this gets merged in sooner?

**Comment by jwhui** [comment]
> @jwhui Do you want me to just open a separate PR to the `ot-docs` repo so that this gets merged in sooner?

@lmnotran , yes, please submit a PR to `ot-docs` whenever you are ready.

**Comment by romacdon** [comment]
@jwhui are you waiting for https://github.com/openthread/ot-docs/pull/8 to be merged before merging this PR?

**Comment by jwhui** [comment]
> @jwhui are you waiting for [openthread/ot-docs#8](https://github.com/openthread/ot-docs/pull/8) to be merged before merging this PR?

@romacdon , we are waiting for https://github.com/openthread/ot-docs/pull/6 before we can remove the remaining example platforms. However, I don't think EFR32 is directly affected by those updates. Would you prefer to remove EFR32 now?

**Comment by romacdon** [comment]
> @romacdon , we are waiting for [openthread/ot-docs#6](https://github.com/openthread/ot-docs/pull/6) before we can remove the remaining example platforms. However, I don't think EFR32 is directly affected by those updates. Would you prefer to remove EFR32 now?

ok, that makes sense.  Do we have an ETA for when that PR will be merged?  Also, do we know when the other examples/platforms/* code will be removed from this repo?

**Comment by romacdon** [comment]
@jwhui is this ready to be merged now?

**Comment by jwhui** [comment]
> @jwhui is this ready to be merged now?

@romacdon , I think we can go ahead and merge this - OK with you?

**Comment by romacdon** [comment]
> > @jwhui is this ready to be merged now?
> 
> @romacdon , I think we can go ahead and merge this - OK with you?

Yup, go for it!

**Pull request merged**
