### PR TITLE
[thci] Fix for ssh connection issue after downloading big syslog

### PR DESCRIPTION
**Pull request by MarekPorwisz**
Python ssh client disconnects and is unable to reconnect after an attempt to download bigger syslog/journal logs.
The solution stores the log in a separate file and downloads part by part. Solution is compatible with ssh and uart connection.

### CODE REVIEW

**Comment by canisLupus1313** [comment]
@MarekPorwisz  I think You should add here cleaning the syslog not to mix up the logs form different runs.

**Comment by canisLupus1313** [comment]
@MarekPorwisz  I think You should add here cleaning the syslog not to mix up the logs form different runs.

**Comment by canisLupus1313** [comment]
@MarekPorwisz  I think You should add here cleaning the syslog not to mix up the logs from different runs.

**Comment by MarekPorwisz** [comment]
> hink You should add here cleaning the syslog not to mix up the logs form different runs.

I don't think this is doable. This defaults to syslog, but could be any user-provided command.

**Comment by jwhui** [comment]
@MarekPorwisz , any plan to move this PR forward?

**Comment by MarekPorwisz** [comment]
> @MarekPorwisz , any plan to move this PR forward?

I didn't get the approval nor the suggestion how to handle custom command, so I don't think there is anything more I can do here.

**Pull request closed without merging**
