### PR TITLE
[nrf52840] use single config for mbedtls build

### PR DESCRIPTION
**Pull request by rlubos**
Due to header inclusion mechanism in IAR, current approach had difficulties to be ported to IAR easily. This PR provides a single config file for both mbedtls configurations making it easier to run on IAR.

Additionaly incorrect inclusion was fixed in `Makefile.am` for nRF platform.

### CODE REVIEW

**Comment by jwhui** [comment]
@rlubos, please resolve merge conflict.

**Comment by rlubos** [comment]
@jwhui Done.

**Comment by rlubos** [comment]
I've found an issue with this PR, please do not merge it until I fix it (hopefully soon).

**Comment by rlubos** [comment]
Sorry for the fuss, I've fixed the compability issue with software version of mbedtls for nRF52840. Is free to merge now again.

**Pull request merged**
