### PR TITLE
[docs] fix typo in sntp docs

### PR DESCRIPTION
**Pull request by CiaranWoodward**

### CODE REVIEW

**Comment by jwhui** [comment]
@CiaranWoodward , thanks for this fix. You'll need to increment `OT_API_VERSION` as well: https://github.com/openthread/openthread/blob/c7192ba7988d6487e6bd8789198ce8196a9c992b/include/openthread/instance.h#L56

**Comment by CiaranWoodward** [comment]
@jwhui No worries, done!

**Review by abtink — APPROVED** [review]
👍

**Review by jwhui — APPROVED** [review]
Thanks! 👍

**Pull request merged**
