### PR TITLE
Set AQ_Retry_Timeout before incrementing AQ_Failures.

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Comment by mszczodrak** [comment]
LGTM 👍

**Comment by librasungirl** [comment]
@jwhui , I have one question: after one address query is sent out, what's the timing for the next address query able to be sent - AQ_Retry_Timeout or (AQ_Timeout + AQ+Retry_Timeout)?

**Comment by jwhui** [comment]
@librasungirl, the only place in the spec that talks about setting `AQ_Retry_Timeout` indicates that it is set after `AQ_Timeout` expires.

**Comment by xiaom-GitHub** [comment]
Sorry, looks like that still keeping the compatible with 1.1 spec temporarily? If so, just as discussion on DEV-824, that the minimum AQ_Retry_Timeout value is 30s when AQ_Failures=1. Or whether we can submit another JIRA for thread specification about this issue and modify the code when the next Thread spec version is published?

**Comment by jwhui** [comment]
@xiaom-GitHub, we should submit a JIRA against the Thread specification.  However, I'm not sure we want to modify the Thread Test spec if we determine the Thread spec is wrong.  If I understand correctly, this PR should be sufficient for addressing the issue in DEV-824, right?

**Comment by librasungirl** [comment]
@jwhui , yes, however the definition about `AQ_Retry_Timeout` easily make people think `AQ_Retry_Timeout` is the least interval between two consecutive address query messages.
`AQ_Retry_Timeout is the time a device must wait before sending another Address Query message`

**Comment by jwhui** [comment]
@librasungirl, the text you quoted is from the `Address Query Set`, which is the conceptual information base that the router maintains for a given address query.  In that context, the definition is correct and the current value stored in `AQ_Retry_Timeout` represents the amount of time remaining before the device can send another Address Query message.

**Comment by librasungirl** [comment]
looks good to me if only for test purpose since there is confusion region in the specification itself.
Meanwhile we might file one JIRA about this to see if there are further clarification.

**Comment by xiaom-GitHub** [comment]
@jwhui Yes, address it. LGTM. Thanks.

**Pull request merged**
