### PR TITLE
[posix] set link type to none explicitly

### PR DESCRIPTION
**Pull request by agners**
Linux kernels with CONFIG_MCTP enable (available in 5.16 or newer) seem to have an issue when setting the link type to ARPHRD_VOID. There seem to be no good reason why ARPHRD_VOID is used. Stick to the default ARPHRD_NONE.

Fixes: #8523

### CODE REVIEW

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Review by canisLupus1313 — APPROVED** [review]

**Comment by canisLupus1313** [comment]
@agners Works on my env. Great job!!!!

**Comment by wgtdkp** [comment]
The `native-commissioner` test case is failing in the CI: https://github.com/openthread/openthread/actions/runs/3690062148/jobs/6250404193 because of this change.

I can consistently reproduce the failure at my local but didn't figured out the root cause yet. Below is the log and traffic.

1. The `native-commissioner` test setup is
    - standalone ot-commissioner acts as a "native commissioner", this is achieved by
    - having the a ot-daemon process set up the wpan0 interface. bring the interface up but don't start thread.
    - having another ot-cli-ftd device act as the leader
    - the commissioner connections to the Leader/BA by the **Link Local Address** of the Leader.

The leader device failed to process the mac frame when setting "ARPHDR_NONE" on the tun interface. The error log looks like this:
```
00:01:14.874 [D] Mac-----------: Received frame from short address 0xfffe
00:01:14.874 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:121, seqnum:140, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:14.876 [D] Mac-----------: Received frame from short address 0xfffe
00:01:14.876 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:126, seqnum:141, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:14.879 [D] Mac-----------: Received frame from short address 0xfffe
00:01:14.879 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:126, seqnum:142, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:14.881 [D] Mac-----------: Received frame from short address 0xfffe
00:01:14.881 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:126, seqnum:143, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:14.881 [D] Mac-----------: Received frame from short address 0xfffe
00:01:14.881 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:112, seqnum:144, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:22.877 [D] Mac-----------: Received frame from short address 0xfffe
00:01:22.877 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:121, seqnum:145, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:22.877 [D] Mac-----------: Received frame from short address 0xfffe
00:01:22.877 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:126, seqnum:146, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:22.880 [D] Mac-----------: Received frame from short address 0xfffe
00:01:22.880 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:126, seqnum:147, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:22.880 [D] Mac-----------: Received frame from short address 0xfffe
00:01:22.880 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:126, seqnum:148, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
00:01:22.881 [D] Mac-----------: Received frame from short address 0xfffe
00:01:22.881 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:112, seqnum:149, type:Data, src:0xfffe, dst:52fda402392b7a55, sec:no, ac
......
```

I got two traffic capture on the wpan0 interface with different ARPHDR_ values:
[void-traffic.zip](https://github.com/openthread/openthread/files/10228362/void-traffic.zip)
[none-traffic.zip](https://github.com/openthread/openthread/files/10228364/none-traffic.zip)

The main difference in the traffic is that, the "Client Hello" of void-traffic.pcap has additional 16 bytes "Linux cooked capture v1" prefix which includes the Link Layer information (i.e. ARPHDR_VOID/65535).
Screenshot from 2022-12-14 22-20-26

Unclear how the packet is transferred to OT simulation devices but it's causing the received to fail to parse the frame. @jwhui @abtink @bukepo @librasungirl

**Comment by agners** [comment]
Hm, interesting finding, so seems this is not an entirely risk free change :fearful: 

Looking through Linux source it does not seem to me that `ARPHRD_VOID` and `ARPHRD_NONE` is handled much differently.

But it seems to be tcpdump (libpcap) which I think Wireshark is using is interpreting it, and probably causes the capture difference:
https://github.com/the-tcpdump-group/libpcap/blob/6ee53e3c01922f5a7127d9430902a9be851bf7a3/pcap-linux.c#L2233-L2239

But not sure why that makes the commissioner fail.

**Review by bukepo — APPROVED** [review]

**Comment by kghost** [comment]
@wgtdkp By looking the TUN device implementation, TUN device packets doesn't contain any mac layer information, with `IFF_NO_PI` it won't include link-layer protocol type flag, so it should not affect our code.

The error message you have pasted probably comes from another bug.

**Review by kghost — APPROVED** [review]

**Review by jwhui — APPROVED** [review]

**Pull request merged**
