### PR TITLE
Revert "[nrf52840] use nrf_security for hardware accelerated cryptography"

### PR DESCRIPTION
**Pull request by jwhui**
Reverts openthread/openthread#4267

### CODE REVIEW

**Comment by KaSroka** [comment]
I think that we may keep it as it is in master - I'll just submit next PR with the update to 0.9.1 nrf_security when it's ready.

**Comment by jwhui** [comment]
@LuDuda, should we keep master as-is (as @KaSroka suggests) or revert #4267?

**Comment by LuDuda** [comment]
I am okay with Kamil's suggestion then. Please close this PR, the update should come very soon.

**Comment by jwhui** [comment]
Sounds good, thanks!

**Pull request closed without merging**
