### PR TITLE
Correct wrong activetimestamp example

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**

### CODE REVIEW

**Comment by jwhui** [comment]
@markus-becker-tridonic-com, thanks for contributing this doc fix! As noted by @googlebot, you'll need to sign the CLA before we can accept this contribution.

**Comment by markus-becker-tridonic-com** [comment]
I am checking internally about the CLA.

**Comment by jwhui** [comment]
Superseded by #4545.

**Comment by markus-becker-tridonic-com** [comment]
Thanks @jwhui. CLA is almost on the finish line now.

**Comment by markus-becker-tridonic-com** [comment]
@googlebot I signed it!

**Comment by jwhui** [comment]
@markus-becker-tridonic-com, thanks for the update!

**Pull request closed without merging**
