### PR TITLE
[thci] allow to specify custom commands

### PR DESCRIPTION
**Pull request by simonlingoogle**
This commit uses `Param9` to specify custom commands for Thread BR THCI to control `otbr-agent`.

### CODE REVIEW

**Comment by simonlingoogle** [comment]
@karthick-grl Could you help review this PR?

**Comment by karthick-grl** [comment]
LGTM

**Review by edmont — COMMENTED** [review]
Seems like an useful feature. Anyhow, could we maybe document somewhere in the THCI file the list of tracked extra parameters? Maybe within `__parseExtraParams()`.

BTW, not big fan of having many private methods in the `OpenThreadTHCI` class since this makes it impossible to override them in the `OpenThread_BR` one.

**Comment by simonlingoogle** [comment]
> Seems like an useful feature. Anyhow, could we maybe document somewhere in the THCI file the list of tracked extra parameters? Maybe within `__parseExtraParams()`.

Doxygen added.

> BTW, not big fan of having many private methods in the `OpenThreadTHCI` class since this makes it impossible to override them in the `OpenThread_BR` one.

It's always easy to rename `__parseExtraParams` to `_parseExtraParams` whenever necessary?

**Review by karthick-grl — APPROVED** [review]

**Review by edmont — APPROVED** [review]
Very nice.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
