### PR TITLE
[mle] further simplifications of logging in MLE

### PR DESCRIPTION
**Pull request by abtink**
This commit updates the logging in `Mle` modules by adding two
enumerations `MessageAction` and `MessageType` to indicate the action
(send, receive, delay, etc.) and the message type in the updated
`Log()` methods.

### CODE REVIEW

**Review by simonlingoogle — APPROVED** [review]
LGTM 👍 

This is wonderful! Thanks.

**Comment by simonlingoogle** [comment]
BTW, I think this can also be extended to more than just for MLE module. It's actually very common for other modules to print similar logs like `Failed to send/receive/process Xxxx Response: error`. Thoughts?

**Comment by abtink** [comment]
Thanks @simonlingoogle. 😃 

> BTW, I think this can also be extended to more than just for MLE module. It's actually very common for other modules to print similar logs like Failed to send/receive/process Xxxx Response: error. Thoughts?

Yes, I agree. I think we can use similar model in other components as well (e.g., `MeshCop` modules seems like a good next candidate). I would say best way is for each component (set of modules) to define its own specific helper `Log()` methods suited for its needs.

**Comment by simonlingoogle** [comment]
> Thanks @simonlingoogle. 😃 
> 
> 
> 
> > BTW, I think this can also be extended to more than just for MLE module. It's actually very common for other modules to print similar logs like Failed to send/receive/process Xxxx Response: error. Thoughts?
> 
> 
> 
> Yes, I agree. I think we can use similar model in other components as well (e.g., `MeshCop` modules seems like a good next candidate). I would say best way is for each component (set of modules) to define its own specific helper `Log()` methods suited for its needs. 

The problem with each component defining its own helper log is that they cannot share the same string constants, unless we provide a universal module for converting action/type to string.

**Review by librasungirl — APPROVED** [review]

**Review by jwhui — APPROVED** [review]

**Pull request merged**
