### PR TITLE
[build] rename ncp_radio to rcp

### PR DESCRIPTION
**Pull request by KaSroka**
Difference between NCP and NCP radio is so big that we should make them more distinguishable. It would be easier for users when they see NCP and RCP.

### CODE REVIEW

**Comment by bukepo** [comment]
Thanks! It seems OpenThread is naming as ot-PROTOCOL-MODE. So I expect names such as ot-cli-ftd, ot-spinel-ftd, ot-spinel-radio. NCP means Network Co-Processor. However it was used to mean the protocol is spinel. RCP also speaks spinel, but only runs some MAC layer. So I think it's acceptable to name as ot-ncp-radio. Maybe we can change to ot-spinel-radio. However, changing the name will involve updating many document. 
 Thoughts? @jwhui

**Comment by KaSroka** [comment]
Hi, I think that `ot-ncp-radio` better suits the host part of openthread in RCP solution. Also, we are using `RCP` name in a few places so we should agree on one naming either `ncp-radio` or `rcp` but definitely not both. All this naming already made some confusion in our team so I can imagine that for consumers it may be even more confusing.

Regarding `ot-cli-radio` what would it do? As it only has radio part we would add some special cli commands for it or something like that?

**Comment by bukepo** [comment]
@KaSroka `radio` mode already supports some cli commands, see https://github.com/openthread/openthread/blob/master/src/core/api/link_raw_api.cpp#L278. Currently these commands are exposed through spinel https://github.com/openthread/openthread/blob/master/src/ncp/ncp_base.cpp#L1286. `radio` mode also supports diag platform extension: https://github.com/openthread/openthread/blob/master/src/core/api/link_raw_api.cpp#L329. This helps diagnostics, so we might add a cli version in future.

`ot-spinel-xxx` would be a better name, because cli app can also run in **NCP**. However, changing the name would involve a lot of documentation update, which I don't think it's necessary for now.

I admit it's not ideal, but will it be less confusing if you take the **ncp** in ot-**ncp**-xxx as indicating the protocol is spinel?

**Comment by abtink** [comment]
After sleeping on it and spending some more time thinking about this today, I am in favor of changing the the name of firmware executable to `ot-rcp`.

I agree that current model of `ot-<app>-<mode>` follows a clear structure and allows us to later add `ot-cli-radio` (which we can still do).

The reason for support of change of name to `ot-rcp`: 
- Most importantly, ease understanding of what the file is from its name, specially for a new person getting started with OT. There has been multiple times where I even confused the `ot-ncp-radio` with the posix-app build. `ot-rcp` will help with this. 
- `ot-ncp-radio` implies that the firmware is for a Network Co-Processor device which is not a good name for radio chip not supporting a full network stack.
- In general, we use the term "RCP" (in the source code and in comments) to refer to the radio chip itself. It makes sense to refer to firmware file as `ot-rcp` as well (making it an exception to naming model of `ot-<app>-<mode>`).  

I won't recommend replacing the term "RCP" in source code (and comments) with "NCP in radio mode" or "NCP-radio" (as it refers to the radio chip). Particularly on posix-app we need a way to distinguish between NCP interface (to talk to a driver) and RCP interface (to talk to the radio chip).

**Comment by turon** [comment]
I also support embracing the RCP naming as @abtink describes.

**Comment by KaSroka** [comment]
Any thoughts of what we should do with this?

**Comment by jwhui** [comment]
@KaSroka, I think there is consensus to move forward with this PR. I've helped resolve merge conflicts on this.

**Pull request merged**
