### PR TITLE
[ip6] prefer ML-EID as realm-local scope source address

### LINKED ISSUE #3268: OpenThread selects RLOC as a source IPv6 address
I'm trying to implement a simple application using OpenThread. Node A transmits a multicast message that is received by B. After some time B transmits a response to A. I've noticed that A uses RLOC as a source address of the multicast request. Because of that, if the network topology is changed between transmission of the request and the response, the response includes outdated RLOC as destination IPv6 address. To prevent this problem nodes should use ML-EID instead. Moreover, Thread specification suggests that applications should not use RLOC as IPv6 addresses.

It looks that usage of RLOC as a source address by default is intentional: https://github.com/openthread/openthread/blob/9a1dc1eeaefe852aa3f51407741d638559e3be39/src/core/net/ip6.cpp#L1088 . I think the reason is that Thread specification requires usage of RLOC as a source address for Thread control messages.

However, I think that the source address selection algorithm should select RLOC for Thread control messages, while it should select ML-EID for application messages. Or should an application manually set the IPv6 source addresses using the `otMessageInfo` structure?

### PR DESCRIPTION
**Pull request by hubertmis**
Fixes #3268

### CODE REVIEW

**Comment by jwhui** [comment]
@hubertmis, thoughts on specifying the source address in `src/core/thread/network_diagnostic.cpp`?

**Comment by hubertmis** [comment]
I can't find any explicit indication in the spec that we shall use RLOC as source address for network diagnostic messages. The only place I can find is chapter 10.6.2 in the Thread 1.1.1 specification.

Anyway, I agree we should use RLOC as source for Thread control messages.
I've found more places where it could be good to select source address manually:

1. https://github.com/openthread/openthread/blob/b9b57cc9e2183ac0abfc185e030594d1a901e057/src/core/meshcop/border_agent.cpp#L409
2. https://github.com/openthread/openthread/blob/b9b57cc9e2183ac0abfc185e030594d1a901e057/src/core/meshcop/border_agent.cpp#L457
3. https://github.com/openthread/openthread/blob/309bd09d7590e8d823db28d3d9dd0f67700c31ec/src/core/meshcop/commissioner.cpp#L1048

Do you agree I should set source address in these functions as well? Or are these exceptions of the rule to use RLOC for control messages?

**Comment by bukepo** [comment]
DTLS uses a fixed messageinfo inside of class Dtls.

**Comment by jwhui** [comment]
@librasungirl, thoughts on whether or not we should require RLOC as source for network diagnostic messages?

**Comment by librasungirl** [comment]
@jwhui , no such requirement either from spec or test harness as far as I am concerned.

It makes sense that application protocols should use ML-EID for IPv6 source address. 
One similar concern is that in a dense network, aggressive address resolution traffic might be introduced if responses are required for such multicast request. For example, DIAG_GET.qry to Realm-Local All Thread Nodes MA.  One further enhancement I could think of is to implement part of '5.5.2.2 Optimizations in Thread 1.1 spec' as an supplement.
```
FTDs MAY update EID-to-RLOC Map Cache entries by inspecting packets being sent/received
via a Thread interface. An FTD MAY add/update EID-to-RLOC Set entries by associating
RLOCs and EIDs contained within the same packet. An FTD MAY also remove EID-to-RLOC
Set entries by observing ICMPv6 error messages.
```

Thoughts?

**Comment by jwhui** [comment]
@librasungirl, are you thinking of learning the RLOC from the MPL Option header and populating the EID-to-RLOC Map Cache appropriately? That would be interesting. Although, we would probably need to consider some protections to ensure that arbitrary messages does not clear the EID-to-RLOC cache of devices unexpectedly.

**Comment by jwhui** [comment]
@hubertmis, thanks for submitting an update to use the RLOC as source address in network diagnostic messages. @bukepo @librasungirl, thoughts? Do we have consensus to use RLOC as source?

**Comment by librasungirl** [comment]
@jwhui , yes, that's what in my thoughts.  
and I am in favor of using RLOC as source in network diagnostic messages.

**Pull request merged**
