### PR TITLE
[tests] add Thread 1.2 all features build test

### PR DESCRIPTION
**Pull request by simonlingoogle**
with or without full logs. 

**This PR can not pass checks before #4848 is merged.**

### CODE REVIEW

**Comment by jwhui** [comment]
> And `PROTOCOL_VERSION` is `2` defined in `config.py`. So when we use Thread 1.2 device, this would fail. As we are moving forward to 1.2, shall we support all these original cases for 1.2?

Is checking that the Version value is set to 2 a part of the Thread Test Specification for Thread 1.1?

**Comment by simonlingoogle** [comment]
> As we are moving forward to 1.2, shall we support all these original cases for 1.2?

I think we need to make sure that 1.2 pass all 1.1 test cases.

**Comment by simonlingoogle** [comment]
> I think with Thread version 1.2, not all functional tests can be passed.

BTW, this PR is just for adding build tests for Thread 1.2, not for functional tests.

**Comment by Irving-cl** [comment]
> > And `PROTOCOL_VERSION` is `2` defined in `config.py`. So when we use Thread 1.2 device, this would fail. As we are moving forward to 1.2, shall we support all these original cases for 1.2?
> 
> Is checking that the Version value is set to 2 a part of the Thread Test Specification for Thread 1.1?

Yes, it's a part of the hread Test Specification for Thread 1.1.

**Comment by Irving-cl** [comment]
> > I think with Thread version 1.2, not all functional tests can be passed.
> 
> BTW, this PR is just for adding build tests for Thread 1.2, not for functional tests.

Ok then. So the issue I proposed won't affect this PR. But we'll need to solve it to introduce 1.2.

**Pull request merged**
