### PR TITLE
[csl] fix `TimerMicro::GetNow()` call in `sub_mac.cpp`

### PR DESCRIPTION
**Pull request by maciejbaczmanski**
Add missing `.GetValue()` for getting values from `TimerMicro`

related PR: https://github.com/openthread/openthread/pull/9568

### CODE REVIEW

**Review by edmont — APPROVED** [review]

**Review by abtink — APPROVED** [review]
👍

**Review by bukepo — COMMENTED** [review]
should we add a test to cover the case OPENTHREAD_CONFIG_MAC_CSL_RECEIVER_LOCAL_TIME_SYNC is enabled?

**Comment by maciejbaczmanski** [comment]
> should we add a test to cover the case OPENTHREAD_CONFIG_MAC_CSL_RECEIVER_LOCAL_TIME_SYNC is enabled?

I think we could add a new job to `simulation-1.2.yml` , which would do a separate build with `OPENTHREAD_CONFIG_MAC_CSL_RECEIVER_LOCAL_TIME_SYNC` enabled and run for example `v1_2_test_csl_transmission.py` test. 
Although, I'm worried if adding a separate build just for one case won't be too time consuming. 
Thoughts @abtink @bukepo ?

**Comment by abtink** [comment]
> I think we could add a new job to simulation-1.2.yml , which would do a separate build with OPENTHREAD_CONFIG_MAC_CSL_RECEIVER_LOCAL_TIME_SYNC enabled and run for example v1_2_test_csl_transmission.py test.
Although, I'm worried if adding a separate build just for one case won't be too time consuming.
Thoughts @abtink @bukepo ?

Adding a test sound useful. 
Maybe can consider restricting the test (which would enable `MAC_CSL_RECEIVER_LOCAL_TIME_SYNC`) to a subset of tests which validate CSL?

**Comment by maciejbaczmanski** [comment]
> > I think we could add a new job to simulation-1.2.yml , which would do a separate build with OPENTHREAD_CONFIG_MAC_CSL_RECEIVER_LOCAL_TIME_SYNC enabled and run for example v1_2_test_csl_transmission.py test.
> > Although, I'm worried if adding a separate build just for one case won't be too time consuming.
> > Thoughts @abtink @bukepo ?
> 
> Adding a test sound useful. Maybe can consider restricting the test (which would enable `MAC_CSL_RECEIVER_LOCAL_TIME_SYNC`) to a subset of tests which validate CSL?

I've found that we can add a separate build with it's own directory to the same job. this way we can save some time and resources on bootstrap, checking crashes, uploading artifacts etc.

**Review by bukepo — APPROVED** [review]

**Review by jwhui — APPROVED** [review]

**Pull request merged**
