### PR TITLE
Add Python3 support to thread-cert.

### PR DESCRIPTION
**Pull request by prfi**
Add support to Python3. Currently tests can be run on Python2 and Python3. #976

### CODE REVIEW

**Comment by jwhui** [comment]
Thanks for working on this.  I tried it out on my setup but ran into the following error:

```bash
/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/sniffer.py:95: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 9003)>
  data, address = socket.fromfd(fd, socket.AF_INET, socket.SOCK_DGRAM).recvfrom(self.RECV_BUFFER_SIZE)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/jonhui/.pyenv/versions/3.5.2/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/jonhui/.pyenv/versions/3.5.2/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/sniffer.py", line 123, in _run
    self._recv(fd)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/sniffer.py", line 97, in _recv
    msg = self._message_factory.create(io.BytesIO(data))
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/message.py", line 296, in create
    ipv6_packet = self._lowpan_parser.parse(lowpan_payload, message_info)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/lowpan.py", line 1093, in parse
    return self._handle_iphc_header(data, message_info)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/lowpan.py", line 1073, in _handle_iphc_header
    return self._ipv6_packet_factory.parse(io.BytesIO(decompressed_data), message_info)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/ipv6.py", line 864, in parse
    upper_layer_protocol = self._parse_upper_layer_protocol(data, next_header, message_info)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/ipv6.py", line 854, in _parse_upper_layer_protocol
    return factory.parse(data, message_info)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/ipv6.py", line 983, in parse
    return UDPDatagram(udp_header, factory.parse(data, message_info))
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/mle.py", line 1163, in parse
    return self._create_mle_secured_message(data, message_info)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/mle.py", line 1148, in _create_mle_secured_message
    dec_data = self._crypto_engine.decrypt(enc_data, mic, message_info)
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/net_crypto.py", line 87, in decrypt
    cipher = AES.new(key, AES.MODE_CCM, nonce, mac_len=self.mic_length)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_CCM'
```

I seem to have the proper python modules installed:

```bash
$ pip list
astroid (1.4.8)
crypto (1.4.1)
isort (4.2.5)
lazy-object-proxy (1.2.2)
mccabe (0.5.2)
Naked (0.1.31)
pexpect (4.2.0)
pip (8.1.1)
ptyprocess (0.5.1)
pycrypto (2.6.1)
pycryptodome (3.4.3)
pylint (1.6.4)
PyYAML (3.12)
queuelib (1.4.2)
requests (2.11.1)
setuptools (20.10.1)
shellescape (3.4.1)
six (1.10.0)
wrapt (1.10.8)
```

Thoughts?

**Comment by prfi** [comment]
There is name collision in packages `pycrypto` and `pycryptodome` (both have module `Crypto`). Probably you have imported `Crypto` from `pycrypto` (which doesn't support AES CCM). To avoid this situation I'm using `virtualenv`.

**Comment by jwhui** [comment]
Yes, that was it.  Thanks.  Now the test succeeds, but I noticed the following warning that occurs repeatedly.  Is this expected?

```bash
/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/sniffer.py:95: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 9003)>
  data, address = socket.fromfd(fd, socket.AF_INET, socket.SOCK_DGRAM).recvfrom(self.RECV_BUFFER_SIZE)
```

**Comment by prfi** [comment]
I don't see this output on my machine. I will try to add fix to current pull request.

**Comment by prfi** [comment]
I've pushed fix.

**Comment by jwhui** [comment]
Tried the updated PR.  I still see the warnings, but also a new exception:

```bash
jonhui@jonhui-macbookpro openthread (NordicSemiconductor-pr/thread-cert-python3-support) $ top_builddir=`pwd` python ./tests/scripts/thread-cert/Cert_5_1_01_RouterAttach.py 
/Users/jonhui/jwhui/openthread/examples/apps/cli/ot-cli-ftd 1
1: whitelist clear
1: whitelist disable
1: childtimeout 100
/Users/jonhui/jwhui/openthread/examples/apps/cli/ot-cli-ftd 2
2: whitelist clear
2: whitelist disable
2: childtimeout 100
1: panid 64206
1: mode rsdn
2: extaddr
1: whitelist add da46903449995e19
1: whitelist enable
2: panid 64206
2: mode rsdn
1: extaddr
2: whitelist add 023c5213ec98f318
2: whitelist enable
2: routerselectionjitter 1
1: ifconfig up
1: thread start
1: state leader
1: state
/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/sniffer.py:103: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 9003)>
  data, address = socket.fromfd(fd, socket.AF_INET, socket.SOCK_DGRAM).recvfrom(self.RECV_BUFFER_SIZE)
2: ifconfig up
2: thread start
/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/sniffer.py:103: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 9003)>
  data, address = socket.fromfd(fd, socket.AF_INET, socket.SOCK_DGRAM).recvfrom(self.RECV_BUFFER_SIZE)
ActiveOperationalDataset is not implemented yet.
2: state
2: ipaddr
MleMessage doesn't contain optional TLV: <class 'mle.MleFrameCounter'>
1: ipaddr
MleMessage doesn't contain optional TLV: <class 'mle.MleFrameCounter'>
2: ipaddr
MleMessage doesn't contain optional TLV: <class 'mle.NetworkData'>
MleMessage doesn't contain optional TLV: <class 'mle.Route64'>
MleMessage doesn't contain optional TLV: <class 'mle.AddressRegistration'>
MleMessage doesn't contain optional TLV: <class 'mle.MleFrameCounter'>
MleMessage doesn't contain optional TLV: <class 'mle.Challenge'>
1: ipaddr
2: ping fdde:ad00:beef:0:0:ff:fe00:fc00
2: ping fdde:ad00:beef:0:0:ff:fe00:bc00
2: ping fdde:ad00:beef:0:8468:ee17:e84a:2873
2: ping fe80:0:0:0:3c:5213:ec98:f318
Exception ignored in: <bound method Sniffer.__del__ of <sniffer.Sniffer object at 0x10e5c9320>>
Traceback (most recent call last):
  File "/Users/jonhui/jwhui/openthread/tests/scripts/thread-cert/sniffer.py", line 89, in __del__
    self._socket.shutdown()
TypeError: shutdown() takes exactly one argument (0 given)
./tests/scripts/thread-cert/Cert_5_1_01_RouterAttach.py:65: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 9003)>
  del self.sniffer
1: thread stop
1: ifconfig down
2: thread stop
2: ifconfig down
1: exit
2: exit
.
----------------------------------------------------------------------
Ran 1 test in 9.837s

OK
```

**Comment by prfi** [comment]
Another fix :) I've checked it manually and seems that it works.

**Comment by jwhui** [comment]
Just verified and it works for me!  Thanks.

**Pull request merged**
