### PR TITLE
[routing-manager] fix build error due to merge conflict

### PR DESCRIPTION
**Pull request by jwhui**
`RemoveExternalRoute` -> `UnpublishExternalRoute`

### CODE REVIEW

**Review by abtink — APPROVED** [review]
LGTM

**Review by simonlingoogle — APPROVED** [review]
LGTM 👍

**Comment by jwhui** [comment]
It appears `test_multi_border_routers.py` is still failing.

```
2022-05-18 00:39:52,816 - INFO - HOST    addrs: ['fdde:ad00:beef:cafe:42:acff:fe13:4', '9101::4', 'fe80::42:acff:fe13:4']
```

```
2022-05-18 00:40:22,838 - INFO - Host<5> $ ping -6 fd9a:d27c:ae99:1:41f8:3a90:b05a:ce7e -I eth0 -c 1 -W 5
5604May 18 00:40:22 8100c543d13f otbr-agent[139]: 00:01:42.199 [D] RadioSelector-: RadioSelector: UpdateOnRx trel - neighbor:[166e0a0000000003 rloc16:0xf800 radio-pref:{trel:255 15.4:255} state:Valid]
5605May 18 00:40:22 8100c543d13f otbr-agent[139]: 00:01:42.199 [I] MeshForwarder-: Received mesh frame, len:105, from:0xf800, msrc:0xf800, mdst:0x4000, hops:3, frag:yes, sec:yes, rss:-20.0, radio:trel
5606May 18 00:40:22 8100c543d13f otbr-agent[139]: 00:01:42.199 [I] MeshForwarder-:     Frag tag:ff6a, offset:0, size:104
5607May 18 00:40:22 8100c543d13f otbr-agent[139]: 00:01:42.199 [I] MeshForwarder-:     IPv6 ICMP6 msg, chksum:0000, ecn:no, prio:normal
5608May 18 00:40:22 8100c543d13f otbr-agent[139]: 00:01:42.199 [I] MeshForwarder-:     src:[9101:0:0:0:0:0:0:4]
5609May 18 00:40:22 8100c543d13f otbr-agent[139]: 00:01:42.199 [I] MeshForwarder-:     dst:[fd9a:d27c:ae99:1:41f8:3a90:b05a:ce7e]
```

The reason for the failure is that the host is using the `9101::` address as the source address.

**Comment by jwhui** [comment]
Merged with #7715

**Pull request closed without merging**
